// Copyright © 2026 MetaX Integrated Circuits (Shanghai) Co., Ltd. All Rights Reserved.
// 
// This software and associated documentation files (hereinafter collectively referred to as
// "Software") is a proprietary commercial software developed by MetaX Integrated Circuits
// (Shanghai) Co., Ltd. and/or its affiliates (hereinafter collectively referred to as “MetaX”).
// The information presented in the Software belongs to MetaX. Without prior written permission
// from MetaX, no entity or individual has the right to obtain a copy of the Software to deal in
// the Software, including but not limited to use, copy, modify, merge, disclose, publish,
// distribute, sublicense, and/or sell copies of the Software or substantial portions of the Software.
// 
// The Software is provided for reference only, without warranty of any kind, either express or
// implied, including but not limited to the warranty of merchantability, fitness for any purpose
// and/or noninfringement. In no case shall MetaX be liable for any claim, damage or other liability
// arising from, out of or in connection with the Software.
// 
// If the Software need to be used in conjunction with any third-party software or open source
// software, the rights to the third-party software or open source software still belong to the
// copyright owners. For details, please refer to the respective notices or licenses. Please comply
// with the provisions of the relevant notices or licenses. If the open source software licenses
// additionally require the disposal of rights related to this Software, please contact MetaX
// immediately and obtain MetaX 's written consent.
// 
// MetaX reserves the right, at its sole discretion, to change, modify, add or remove portions of the
// Software, at any time. MetaX reserves all the right for the final explanation.

// WARNING: This file has automatically been generated on Thu, 29 Jan 2026 15:10:54 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "MxSml.h"
#include "MxSmlMcm.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

