// Copyright © 2026 MetaX Integrated Circuits (Shanghai) Co., Ltd. All Rights Reserved.
//
// This software and associated documentation files (hereinafter collectively referred to as
// "Software") is a proprietary commercial software developed by MetaX Integrated Circuits
// (Shanghai) Co., Ltd. and/or its affiliates (hereinafter collectively referred to as “MetaX”).
// The information presented in the Software belongs to MetaX. Without prior written permission
// from MetaX, no entity or individual has the right to obtain a copy of the Software to deal in
// the Software, including but not limited to use, copy, modify, merge, disclose, publish,
// distribute, sublicense, and/or sell copies of the Software or substantial portions of the Software.
//
// The Software is provided for reference only, without warranty of any kind, either express or
// implied, including but not limited to the warranty of merchantability, fitness for any purpose
// and/or noninfringement. In no case shall MetaX be liable for any claim, damage or other liability
// arising from, out of or in connection with the Software.
//
// If the Software need to be used in conjunction with any third-party software or open source
// software, the rights to the third-party software or open source software still belong to the
// copyright owners. For details, please refer to the respective notices or licenses. Please comply
// with the provisions of the relevant notices or licenses. If the open source software licenses
// additionally require the disposal of rights related to this Software, please contact MetaX
// immediately and obtain MetaX 's written consent.
//
// MetaX reserves the right, at its sole discretion, to change, modify, add or remove portions of the
// Software, at any time. MetaX reserves all the right for the final explanation.

// WARNING: This file has automatically been generated on Tue, 09 Jun 2026 11:08:59 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package mxsml

/*
#cgo linux LDFLAGS: -Wl,--export-dynamic -Wl,--unresolved-symbols=ignore-in-object-files
#include "MxSml.h"
#include "MxSmlMcm.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const (
	// MXSML_DEVICE_BDF_ID_SIZE as defined in MxSml.h
	MXSML_DEVICE_BDF_ID_SIZE = 32
	// MXSML_DEVICE_UUID_SIZE as defined in MxSml.h
	MXSML_DEVICE_UUID_SIZE = 96
	// MXSML_DEVICE_NAME_SIZE as defined in MxSml.h
	MXSML_DEVICE_NAME_SIZE = 32
	// MXSML_RAS_STATUS_REG_NUM as defined in MxSml.h
	MXSML_RAS_STATUS_REG_NUM = 128
	// MXSML_RAS_ERROR_REG_NUM as defined in MxSml.h
	MXSML_RAS_ERROR_REG_NUM = 128
	// MXSML_EEPROM_INFO_SIZE as defined in MxSml.h
	MXSML_EEPROM_INFO_SIZE = 1024
	// MXSML_VIRTUAL_DEVICE_SIZE as defined in MxSml.h
	MXSML_VIRTUAL_DEVICE_SIZE = 128
	// MXSML_PROCESS_NAME_SIZE as defined in MxSml.h
	MXSML_PROCESS_NAME_SIZE = 64
	// MXSML_MAX_GPU_NUM_USED_BY_PROCESS as defined in MxSml.h
	MXSML_MAX_GPU_NUM_USED_BY_PROCESS = 64
	// MXSML_INIT_FLAG_NORMAL as defined in MxSml.h
	MXSML_INIT_FLAG_NORMAL = 0
	// MXSML_INIT_FLAG_REINIT as defined in MxSml.h
	MXSML_INIT_FLAG_REINIT = 1
	// MXSML_BOARD_SERIAL_SIZE as defined in MxSml.h
	MXSML_BOARD_SERIAL_SIZE = 32
	// MXSML_METAX_LINK_NUM as defined in MxSml.h
	MXSML_METAX_LINK_NUM = 7
	// MXSML_VBIOS_BIN_PATH_SIZE as defined in MxSml.h
	MXSML_VBIOS_BIN_PATH_SIZE = 150
	// MXSML_MIN_PCI_DELAY as defined in MxSml.h
	MXSML_MIN_PCI_DELAY = 1
	// MXSML_MAX_PCI_DELAY as defined in MxSml.h
	MXSML_MAX_PCI_DELAY = 10000
	// MXSML_VERSION_INFO_SIZE as defined in MxSml.h
	MXSML_VERSION_INFO_SIZE = 64
	// MXSML_CHIP_SERIAL_SIZE as defined in MxSml.h
	MXSML_CHIP_SERIAL_SIZE = 32
	// MXSML_MAX_SMP_NUM as defined in MxSml.h
	MXSML_MAX_SMP_NUM = 2
	// MXSML_MAX_CCX_NUM as defined in MxSml.h
	MXSML_MAX_CCX_NUM = 4
	// MXSML_OPTICAL_MODULE_INFO_SIZE as defined in MxSml.h
	MXSML_OPTICAL_MODULE_INFO_SIZE = 32
	// MXSML_OPTICAL_POWER_RX_NUM as defined in MxSml.h
	MXSML_OPTICAL_POWER_RX_NUM = 8
	// MXSML_MAX_SGPU_COUNT as defined in MxSml.h
	MXSML_MAX_SGPU_COUNT = 16
	// MXSML_EVENT_TIME_LENGTH as defined in MxSml.h
	MXSML_EVENT_TIME_LENGTH = 20
	// MXSML_EVENT_NAME_LENGTH as defined in MxSml.h
	MXSML_EVENT_NAME_LENGTH = 64
	// MXSML_MAX_EVENT_NUM as defined in MxSml.h
	MXSML_MAX_EVENT_NUM = 32
	// MXSML_DEVICE_UNAVAILABLE_REASON_SIZE as defined in MxSml.h
	MXSML_DEVICE_UNAVAILABLE_REASON_SIZE = 64
	// MXSML_EVENT_DATA_SIZE as defined in MxSml.h
	MXSML_EVENT_DATA_SIZE = 1024
	// MXSML_MAX_DIE_NUM as defined in mxsml/MxSmlMcm.h:47
	MXSML_MAX_DIE_NUM = 2
	// mxSmlEventTypeEid as defined in MxSml.h
	MXSML_mxSmlEventTypeEid = 1
)

// MxSmlReturn as declared in MxSml.h
type MxSmlReturn int32

// MxSmlReturn enumeration from MxSml.h
const (
	MXSML_Success                MxSmlReturn = iota
	MXSML_Failure                MxSmlReturn = 1
	MXSML_NoDevice               MxSmlReturn = 2
	MXSML_OperationNotSupport    MxSmlReturn = 3
	MXSML_SysfsError             MxSmlReturn = 4
	MXSML_SysfsWriteError        MxSmlReturn = 5
	MXSML_InvalidDeviceId        MxSmlReturn = 6
	MXSML_InvalidDieId           MxSmlReturn = 7
	MXSML_PermissionDenied       MxSmlReturn = 8
	MXSML_InvalidInput           MxSmlReturn = 9
	MXSML_InsufficientSize       MxSmlReturn = 10
	MXSML_Reserved3              MxSmlReturn = 11
	MXSML_IOControlFailure       MxSmlReturn = 12
	MXSML_MmapFailure            MxSmlReturn = 13
	MXSML_UnMmapFailure          MxSmlReturn = 14
	MXSML_InvalidInputForMmap    MxSmlReturn = 15
	MXSML_Reserved1              MxSmlReturn = 16
	MXSML_Reserved2              MxSmlReturn = 17
	MXSML_TargetVfNotFound       MxSmlReturn = 18
	MXSML_InvalidFrequency       MxSmlReturn = 19
	MXSML_FlrNotReady            MxSmlReturn = 20
	MXSML_OpenDeviceFileFailure  MxSmlReturn = 21
	MXSML_CloseDeviceFileFailure MxSmlReturn = 22
	MXSML_BusyDevice             MxSmlReturn = 23
	MXSML_MmioNotEnough          MxSmlReturn = 24
	MXSML_GetPciBridgeFailure    MxSmlReturn = 25
	MXSML_LoadDllFailure         MxSmlReturn = 26
)

// MxSmlDpmIp as declared in MxSml.h
type MxSmlDpmIp int32

// MxSmlDpmIp enumeration from MxSml.h
const (
	MXSML_Dpm_Dla      MxSmlDpmIp = iota
	MXSML_Dpm_Xcore    MxSmlDpmIp = 1
	MXSML_Dpm_Mc       MxSmlDpmIp = 2
	MXSML_Dpm_Soc      MxSmlDpmIp = 3
	MXSML_Dpm_Dnoc     MxSmlDpmIp = 4
	MXSML_Dpm_Vpue     MxSmlDpmIp = 5
	MXSML_Dpm_Vpud     MxSmlDpmIp = 6
	MXSML_Dpm_Hbm      MxSmlDpmIp = 7
	MXSML_Dpm_G2d      MxSmlDpmIp = 8
	MXSML_Dpm_HbmPower MxSmlDpmIp = 9
	MXSML_Dpm_Ccx      MxSmlDpmIp = 10
	MXSML_Dpm_Ip_Group MxSmlDpmIp = 11
	MXSML_Dpm_Dma      MxSmlDpmIp = 12
	MXSML_Dpm_Csc      MxSmlDpmIp = 13
	MXSML_Dpm_Eth      MxSmlDpmIp = 14
	MXSML_Dpm_Didt     MxSmlDpmIp = 15
	MXSML_Dpm_Reserved MxSmlDpmIp = 16
)

// MxSmlPciPowerState as declared in MxSml.h
type MxSmlPciPowerState int32

// MxSmlPciPowerState enumeration from MxSml.h
const (
	MXSML_Power_Pci_State_D0     MxSmlPciPowerState = iota
	MXSML_Power_Pci_State_D3hot  MxSmlPciPowerState = 1
	MXSML_Power_Pci_State_D3cold MxSmlPciPowerState = 2
)

// MxSmlRasIp as declared in MxSml.h
type MxSmlRasIp int32

// MxSmlRasIp enumeration from MxSml.h
const (
	MXSML_Ras_mc     MxSmlRasIp = iota
	MXSML_Ras_pcie   MxSmlRasIp = 1
	MXSML_Ras_fuse   MxSmlRasIp = 2
	MXSML_Ras_g2d    MxSmlRasIp = 3
	MXSML_Ras_int    MxSmlRasIp = 4
	MXSML_Ras_hag    MxSmlRasIp = 5
	MXSML_Ras_metalk MxSmlRasIp = 6
	MXSML_Ras_smp0   MxSmlRasIp = 7
	MXSML_Ras_smp1   MxSmlRasIp = 8
	MXSML_Ras_ccx0   MxSmlRasIp = 9
	MXSML_Ras_ccx1   MxSmlRasIp = 10
	MXSML_Ras_ccx2   MxSmlRasIp = 11
	MXSML_Ras_ccx3   MxSmlRasIp = 12
	MXSML_Ras_dla0   MxSmlRasIp = 13
	MXSML_Ras_dla1   MxSmlRasIp = 14
	MXSML_Ras_vpue0  MxSmlRasIp = 15
	MXSML_Ras_vpue1  MxSmlRasIp = 16
	MXSML_Ras_vpud0  MxSmlRasIp = 17
	MXSML_Ras_vpud1  MxSmlRasIp = 18
	MXSML_Ras_vpud2  MxSmlRasIp = 19
	MXSML_Ras_vpud3  MxSmlRasIp = 20
	MXSML_Ras_vpud4  MxSmlRasIp = 21
	MXSML_Ras_vpud5  MxSmlRasIp = 22
	MXSML_Ras_vpud6  MxSmlRasIp = 23
	MXSML_Ras_vpud7  MxSmlRasIp = 24
	MXSML_Ras_dma0   MxSmlRasIp = 25
	MXSML_Ras_dma1   MxSmlRasIp = 26
	MXSML_Ras_dma2   MxSmlRasIp = 27
	MXSML_Ras_dma3   MxSmlRasIp = 28
	MXSML_Ras_dma4   MxSmlRasIp = 29
	MXSML_Ras_mcctl0 MxSmlRasIp = 30
	MXSML_Ras_mcctl1 MxSmlRasIp = 31
	MXSML_Ras_mcctl2 MxSmlRasIp = 32
	MXSML_Ras_mcctl3 MxSmlRasIp = 33
	MXSML_Ras_dhub1  MxSmlRasIp = 34
	MXSML_Ras_dhub2  MxSmlRasIp = 35
	MXSML_Ras_dhub3  MxSmlRasIp = 36
	MXSML_Ras_dhub4  MxSmlRasIp = 37
	MXSML_Ras_dhub5  MxSmlRasIp = 38
	MXSML_Ras_dhub6  MxSmlRasIp = 39
	MXSML_Ras_dhub7  MxSmlRasIp = 40
	MXSML_Ras_ath    MxSmlRasIp = 41
	MXSML_Ras_atul20 MxSmlRasIp = 42
	MXSML_Ras_atul21 MxSmlRasIp = 43
	MXSML_Ras_xsc    MxSmlRasIp = 44
	MXSML_Ras_ce     MxSmlRasIp = 45
	MXSML_Ras_eth    MxSmlRasIp = 46
	MXSML_Ras_ethsc  MxSmlRasIp = 47
)

// MxSmlRasIp_v2 as declared in MxSml.h
type MxSmlRasIp_v2 int32

// MxSmlRasIp_v2 enumeration from MxSml.h
const (
	MXSML_Ras_mxlk    MxSmlRasIp_v2 = iota
	MXSML_Ras_vpue    MxSmlRasIp_v2 = 1
	MXSML_Ras_vpud    MxSmlRasIp_v2 = 2
	MXSML_Ras_mc_v2   MxSmlRasIp_v2 = 3
	MXSML_Ras_pcie_v2 MxSmlRasIp_v2 = 4
	MXSML_Ras_eth_v2  MxSmlRasIp_v2 = 5
	MXSML_Ras_unknown MxSmlRasIp_v2 = 100
)

// MxSmlRasErrorType as declared in MxSml.h
type MxSmlRasErrorType int32

// MxSmlRasErrorType enumeration from MxSml.h
const (
	MXSML_Ras_Error_ue    MxSmlRasErrorType = iota
	MXSML_Ras_Error_ce    MxSmlRasErrorType = 1
	MXSML_Ras_Error_fatal MxSmlRasErrorType = 2
	MXSML_Ras_Error_re    MxSmlRasErrorType = 3
)

// MxSmlDeviceBrand as declared in MxSml.h
type MxSmlDeviceBrand int32

// MxSmlDeviceBrand enumeration from MxSml.h
const (
	MXSML_Brand_Unknown MxSmlDeviceBrand = iota
	MXSML_Brand_N       MxSmlDeviceBrand = 1
	MXSML_Brand_C       MxSmlDeviceBrand = 2
	MXSML_Brand_G       MxSmlDeviceBrand = 3
)

// MxSmlDeviceVirtualizationMode as declared in MxSml.h
type MxSmlDeviceVirtualizationMode int32

// MxSmlDeviceVirtualizationMode enumeration from MxSml.h
const (
	MXSML_Virtualization_Mode_None MxSmlDeviceVirtualizationMode = iota
	MXSML_Virtualization_Mode_Pf   MxSmlDeviceVirtualizationMode = 1
	MXSML_Virtualization_Mode_Vf   MxSmlDeviceVirtualizationMode = 2
)

// MxSmlFwIpName as declared in MxSml.h
type MxSmlFwIpName int32

// MxSmlFwIpName enumeration from MxSml.h
const (
	MXSML_Fw_IpName_SMP0  MxSmlFwIpName = iota
	MXSML_Fw_IpName_SMP1  MxSmlFwIpName = 1
	MXSML_Fw_IpName_CCX0  MxSmlFwIpName = 2
	MXSML_Fw_IpName_CCX1  MxSmlFwIpName = 3
	MXSML_Fw_IpName_CCX2  MxSmlFwIpName = 4
	MXSML_Fw_IpName_CCX3  MxSmlFwIpName = 5
	MXSML_Fw_IpName_XCORE MxSmlFwIpName = 6
	MXSML_Fw_IpName_ETH   MxSmlFwIpName = 7
	MXSML_Fw_IpName_DISP  MxSmlFwIpName = 8
	MXSML_Fw_IpName_ALL   MxSmlFwIpName = 9
)

// MxSmlLoglevel as declared in MxSml.h
type MxSmlLoglevel int32

// MxSmlLoglevel enumeration from MxSml.h
const (
	MXSML_Loglevel_NONE    MxSmlLoglevel = iota
	MXSML_Loglevel_FATAL   MxSmlLoglevel = 1
	MXSML_Loglevel_ERROR   MxSmlLoglevel = 2
	MXSML_Loglevel_WARN    MxSmlLoglevel = 3
	MXSML_Loglevel_INFO    MxSmlLoglevel = 4
	MXSML_Loglevel_DEBUG   MxSmlLoglevel = 5
	MXSML_Loglevel_VERBOSE MxSmlLoglevel = 6
	MXSML_Loglevel_UNKNOWN MxSmlLoglevel = 7
)

// MxSmlPciGen as declared in MxSml.h
type MxSmlPciGen int32

// MxSmlPciGen enumeration from MxSml.h
const (
	MXSML_PciGen_1 MxSmlPciGen = 1
	MXSML_PciGen_2 MxSmlPciGen = 2
	MXSML_PciGen_3 MxSmlPciGen = 3
	MXSML_PciGen_4 MxSmlPciGen = 4
	MXSML_PciGen_5 MxSmlPciGen = 5
)

// MxSmlGpuTopologyLevel as declared in MxSml.h
type MxSmlGpuTopologyLevel int32

// MxSmlGpuTopologyLevel enumeration from MxSml.h
const (
	MXSML_TOPOLOGY_INTERNAL   MxSmlGpuTopologyLevel = iota
	MXSML_TOPOLOGY_SINGLE     MxSmlGpuTopologyLevel = 1
	MXSML_TOPOLOGY_MULTIPLE   MxSmlGpuTopologyLevel = 2
	MXSML_TOPOLOGY_HOSTBRIDGE MxSmlGpuTopologyLevel = 3
	MXSML_TOPOLOGY_NODE       MxSmlGpuTopologyLevel = 4
	MXSML_TOPOLOGY_METAXLINK  MxSmlGpuTopologyLevel = 5
	MXSML_TOPOLOGY_SYSTEM     MxSmlGpuTopologyLevel = 6
	MXSML_TOPOLOGY_ETH        MxSmlGpuTopologyLevel = 7
	MXSML_TOPOLOGY_UNDEFINED  MxSmlGpuTopologyLevel = 8
)

// MxSmlVersionUnit as declared in MxSml.h
type MxSmlVersionUnit int32

// MxSmlVersionUnit enumeration from MxSml.h
const (
	MXSML_Version_Bios   MxSmlVersionUnit = iota
	MXSML_Version_Driver MxSmlVersionUnit = 1
	MXSML_Version_Smp0   MxSmlVersionUnit = 2
	MXSML_Version_Smp1   MxSmlVersionUnit = 3
	MXSML_Version_Ccx0   MxSmlVersionUnit = 4
	MXSML_Version_Ccx1   MxSmlVersionUnit = 5
	MXSML_Version_Ccx2   MxSmlVersionUnit = 6
	MXSML_Version_Ccx3   MxSmlVersionUnit = 7
)

// MxSmlUsageIp as declared in MxSml.h
type MxSmlUsageIp int32

// MxSmlUsageIp enumeration from MxSml.h
const (
	MXSML_Usage_Dla   MxSmlUsageIp = iota
	MXSML_Usage_Vpue  MxSmlUsageIp = 1
	MXSML_Usage_Vpud  MxSmlUsageIp = 2
	MXSML_Usage_G2d   MxSmlUsageIp = 3
	MXSML_Usage_Xcore MxSmlUsageIp = 4
)

// MxSmlDeviceType as declared in MxSml.h
type MxSmlDeviceType int32

// MxSmlDeviceType enumeration from MxSml.h
const (
	MXSML_Device_Unknown MxSmlDeviceType = iota
)

// MxSmlPmbusUnit as declared in MxSml.h
type MxSmlPmbusUnit int32

// MxSmlPmbusUnit enumeration from MxSml.h
const (
	MXSML_Pmbus_Soc   MxSmlPmbusUnit = iota
	MXSML_Pmbus_Core  MxSmlPmbusUnit = 1
	MXSML_Pmbus_Hbm   MxSmlPmbusUnit = 2
	MXSML_Pmbus_Pcie  MxSmlPmbusUnit = 3
	MXSML_Pmbus_Hbm2  MxSmlPmbusUnit = 4
	MXSML_Pmbus_Pcie2 MxSmlPmbusUnit = 5
)

// MxSmlTemperatureSensors as declared in MxSml.h
type MxSmlTemperatureSensors int32

// MxSmlTemperatureSensors enumeration from MxSml.h
const (
	MXSML_Temperature_Hotspot           MxSmlTemperatureSensors = iota
	MXSML_Temperature_HotLimit          MxSmlTemperatureSensors = 1
	MXSML_Temperature_Soc               MxSmlTemperatureSensors = 2
	MXSML_Temperature_Core              MxSmlTemperatureSensors = 3
	MXSML_Temperature_Ccx_Dnoc          MxSmlTemperatureSensors = 4
	MXSML_Temperature_Csc_Fuse          MxSmlTemperatureSensors = 5
	MXSML_Temperature_Ccx_Dla_Vpue1_Ath MxSmlTemperatureSensors = 6
	MXSML_Temperature_Vpue1             MxSmlTemperatureSensors = 7
	MXSML_Temperature_Vpue0             MxSmlTemperatureSensors = 8
	MXSML_Temperature_Atul2             MxSmlTemperatureSensors = 9
	MXSML_Temperature_Dla1              MxSmlTemperatureSensors = 10
	MXSML_Temperature_Dla0              MxSmlTemperatureSensors = 11
	MXSML_Temperature_Emc0              MxSmlTemperatureSensors = 12
	MXSML_Temperature_Emc1              MxSmlTemperatureSensors = 13
	MXSML_Temperature_Sgm               MxSmlTemperatureSensors = 14
	MXSML_Temperature_Hbm               MxSmlTemperatureSensors = 15
)

// MxSmlClockIp as declared in MxSml.h
type MxSmlClockIp int32

// MxSmlClockIp enumeration from MxSml.h
const (
	MXSML_Clock_Csc   MxSmlClockIp = iota
	MXSML_Clock_Dla   MxSmlClockIp = 1
	MXSML_Clock_Mc    MxSmlClockIp = 2
	MXSML_Clock_Mc0   MxSmlClockIp = 3
	MXSML_Clock_Mc1   MxSmlClockIp = 4
	MXSML_Clock_Vpue  MxSmlClockIp = 5
	MXSML_Clock_Vpud  MxSmlClockIp = 6
	MXSML_Clock_Soc   MxSmlClockIp = 7
	MXSML_Clock_Dnoc  MxSmlClockIp = 8
	MXSML_Clock_G2D   MxSmlClockIp = 9
	MXSML_Clock_Ccx   MxSmlClockIp = 10
	MXSML_Clock_Xcore MxSmlClockIp = 11
)

// MxSmlMetaXLinkType as declared in MxSml.h
type MxSmlMetaXLinkType int32

// MxSmlMetaXLinkType enumeration from MxSml.h
const (
	MXSML_MetaXLink_Input  MxSmlMetaXLinkType = iota
	MXSML_MetaXLink_Target MxSmlMetaXLinkType = 1
)

// MxSmlMetaXLinkState as declared in MxSml.h
type MxSmlMetaXLinkState int32

// MxSmlMetaXLinkState enumeration from MxSml.h
const (
	MXSML_MetaXLink_State_Enabled                          MxSmlMetaXLinkState = iota
	MXSML_MetaXLink_State_Smi_Disabled                     MxSmlMetaXLinkState = 1
	MXSML_MetaXLink_State_Turn_On_SRIOV_Disabled           MxSmlMetaXLinkState = 2
	MXSML_MetaXLink_State_Invalid_GpuNum_For_Topo_Disabled MxSmlMetaXLinkState = 3
	MXSML_MetaXLink_State_Training_Failed_Disabled         MxSmlMetaXLinkState = 4
)

// MxSmlMxlkPortState as declared in MxSml.h
type MxSmlMxlkPortState int32

// MxSmlMxlkPortState enumeration from MxSml.h
const (
	MXSML_Mxlk_Port_State_NoTraining            MxSmlMxlkPortState = iota
	MXSML_Mxlk_Port_State_Up                    MxSmlMxlkPortState = 1
	MXSML_Mxlk_Port_State_Down_Optical_InPlace  MxSmlMxlkPortState = 2
	MXSML_Mxlk_Port_State_Down_Optical_OutPlace MxSmlMxlkPortState = 3
	MXSML_Mxlk_Port_State_Down_Optical_NoUse    MxSmlMxlkPortState = 4
	MXSML_Mxlk_Port_State_NoUse                 MxSmlMxlkPortState = 5
)

// MxSmlPciEventType as declared in MxSml.h
type MxSmlPciEventType int32

// MxSmlPciEventType enumeration from MxSml.h
const (
	MXSML_Pci_Event_AER_UE MxSmlPciEventType = iota
	MXSML_Pci_Event_AER_CE MxSmlPciEventType = 1
	MXSML_Pci_Event_SYNFLD MxSmlPciEventType = 2
	MXSML_Pci_Event_DBE    MxSmlPciEventType = 3
	MXSML_Pci_Event_MMIO   MxSmlPciEventType = 4
)

// MxSmlSchedClass as declared in MxSml.h
type MxSmlSchedClass int32

// MxSmlSchedClass enumeration from MxSml.h
const (
	MXSML_SCHED_CLASS_BEST_EFFORT MxSmlSchedClass = iota
	MXSML_SCHED_CLASS_FIXED_SHARE MxSmlSchedClass = 1
	MXSML_SCHED_CLASS_BURST_SHARE MxSmlSchedClass = 2
	MXSML_SCHED_CLASS_MAX         MxSmlSchedClass = 3
)
