// Copyright © 2026 MetaX Integrated Circuits (Shanghai) Co., Ltd. All Rights Reserved.
//
// This software and associated documentation files (hereinafter collectively referred to as
// "Software") is a proprietary commercial software developed by MetaX Integrated Circuits
// (Shanghai) Co., Ltd. and/or its affiliates (hereinafter collectively referred to as “MetaX”).
// The information presented in the Software belongs to MetaX. Without prior written permission
// from MetaX, no entity or individual has the right to obtain a copy of the Software to deal in
// the Software, including but not limited to use, copy, modify, merge, disclose, publish,
// distribute, sublicense, and/or sell copies of the Software or substantial portions of the Software.
//
// The Software is provided for reference only, without warranty of any kind, either express or
// implied, including but not limited to the warranty of merchantability, fitness for any purpose
// and/or noninfringement. In no case shall MetaX be liable for any claim, damage or other liability
// arising from, out of or in connection with the Software.
//
// If the Software need to be used in conjunction with any third-party software or open source
// software, the rights to the third-party software or open source software still belong to the
// copyright owners. For details, please refer to the respective notices or licenses. Please comply
// with the provisions of the relevant notices or licenses. If the open source software licenses
// additionally require the disposal of rights related to this Software, please contact MetaX
// immediately and obtain MetaX 's written consent.
//
// MetaX reserves the right, at its sole discretion, to change, modify, add or remove portions of the
// Software, at any time. MetaX reserves all the right for the final explanation.

// WARNING: This file has automatically been generated on Tue, 09 Jun 2026 11:08:59 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package mxsml

/*
#cgo linux LDFLAGS: -Wl,--export-dynamic -Wl,--unresolved-symbols=ignore-in-object-files
#include "MxSml.h"
#include "MxSmlMcm.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import (
	"runtime"
	"unsafe"
)

// mxSmlInit function as declared in MxSml.h
func mxSmlInit() MxSmlReturn {
	__ret := C.mxSmlInit()
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlInitWithFlags function as declared in MxSml.h
func mxSmlInitWithFlags(Flags uint32) MxSmlReturn {
	cFlags, cFlagsAllocMap := (C.uint)(Flags), cgoAllocsUnknown
	__ret := C.mxSmlInitWithFlags(cFlags)
	runtime.KeepAlive(cFlagsAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetDeviceCount function as declared in MxSml.h
func mxSmlGetDeviceCount() uint32 {
	__ret := C.mxSmlGetDeviceCount()
	__v := (uint32)(__ret)
	return __v
}

// mxSmlGetPfDeviceCount function as declared in MxSml.h
func mxSmlGetPfDeviceCount() uint32 {
	__ret := C.mxSmlGetPfDeviceCount()
	__v := (uint32)(__ret)
	return __v
}

// mxSmlGetVirtualDevicesByPhysicalId function as declared in MxSml.h
func mxSmlGetVirtualDevicesByPhysicalId(PhyDeviceId uint32, DeviceIds *MxSmlVirtualDeviceIds) MxSmlReturn {
	cPhyDeviceId, cPhyDeviceIdAllocMap := (C.uint)(PhyDeviceId), cgoAllocsUnknown
	cDeviceIds, cDeviceIdsAllocMap := (*C.mxSmlVirtualDeviceIds_t)(unsafe.Pointer(DeviceIds)), cgoAllocsUnknown
	__ret := C.mxSmlGetVirtualDevicesByPhysicalId(cPhyDeviceId, cDeviceIds)
	runtime.KeepAlive(cDeviceIdsAllocMap)
	runtime.KeepAlive(cPhyDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetDeviceInfo function as declared in MxSml.h
func mxSmlGetDeviceInfo(DeviceId uint32, DeviceInfo *MxSmlDeviceInfo) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cDeviceInfo, cDeviceInfoAllocMap := (*C.mxSmlDeviceInfo_t)(unsafe.Pointer(DeviceInfo)), cgoAllocsUnknown
	__ret := C.mxSmlGetDeviceInfo(cDeviceId, cDeviceInfo)
	runtime.KeepAlive(cDeviceInfoAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetAllLimitedDevices function as declared in MxSml.h
func mxSmlGetAllLimitedDevices(DeviceIds *MxSmlLimitedDeviceIds) MxSmlReturn {
	cDeviceIds, cDeviceIdsAllocMap := (*C.mxSmlLimitedDeviceIds_t)(unsafe.Pointer(DeviceIds)), cgoAllocsUnknown
	__ret := C.mxSmlGetAllLimitedDevices(cDeviceIds)
	runtime.KeepAlive(cDeviceIdsAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetLimitedDeviceInfo function as declared in MxSml.h
func mxSmlGetLimitedDeviceInfo(DeviceId uint32, DeviceInfo *MxSmlDeviceInfo) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cDeviceInfo, cDeviceInfoAllocMap := (*C.mxSmlDeviceInfo_t)(unsafe.Pointer(DeviceInfo)), cgoAllocsUnknown
	__ret := C.mxSmlGetLimitedDeviceInfo(cDeviceId, cDeviceInfo)
	runtime.KeepAlive(cDeviceInfoAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetPmbusInfo function as declared in MxSml.h
func mxSmlGetPmbusInfo(DeviceId uint32, PmbusUnit MxSmlPmbusUnit, PmbusInfo *MxSmlPmbusInfo) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cPmbusUnit, cPmbusUnitAllocMap := (C.mxSmlPmbusUnit_t)(PmbusUnit), cgoAllocsUnknown
	cPmbusInfo, cPmbusInfoAllocMap := (*C.mxSmlPmbusInfo_t)(unsafe.Pointer(PmbusInfo)), cgoAllocsUnknown
	__ret := C.mxSmlGetPmbusInfo(cDeviceId, cPmbusUnit, cPmbusInfo)
	runtime.KeepAlive(cPmbusInfoAllocMap)
	runtime.KeepAlive(cPmbusUnitAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetTemperatureInfo function as declared in MxSml.h
func mxSmlGetTemperatureInfo(DeviceId uint32, TemperatureType MxSmlTemperatureSensors, Temperature *int32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cTemperatureType, cTemperatureTypeAllocMap := (C.mxSmlTemperatureSensors_t)(TemperatureType), cgoAllocsUnknown
	cTemperature, cTemperatureAllocMap := (*C.int)(unsafe.Pointer(Temperature)), cgoAllocsUnknown
	__ret := C.mxSmlGetTemperatureInfo(cDeviceId, cTemperatureType, cTemperature)
	runtime.KeepAlive(cTemperatureAllocMap)
	runtime.KeepAlive(cTemperatureTypeAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetBoardPowerInfo function as declared in MxSml.h
func mxSmlGetBoardPowerInfo(DeviceId uint32, InfoSize *uint32, BoardInfo *MxSmlBoardWayElectricInfo) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cInfoSize, cInfoSizeAllocMap := (*C.uint)(unsafe.Pointer(InfoSize)), cgoAllocsUnknown
	cBoardInfo, cBoardInfoAllocMap := (*C.mxSmlBoardWayElectricInfo_t)(unsafe.Pointer(BoardInfo)), cgoAllocsUnknown
	__ret := C.mxSmlGetBoardPowerInfo(cDeviceId, cInfoSize, cBoardInfo)
	runtime.KeepAlive(cBoardInfoAllocMap)
	runtime.KeepAlive(cInfoSizeAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetDpmMaxPerfLevel function as declared in MxSml.h
func mxSmlGetDpmMaxPerfLevel(DeviceId uint32, DpmMaxLevel *MxSmlMxcDpmPerfLevel) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cDpmMaxLevel, cDpmMaxLevelAllocMap := (*C.mxSmlMxcDpmPerfLevel_t)(unsafe.Pointer(DpmMaxLevel)), cgoAllocsUnknown
	__ret := C.mxSmlGetDpmMaxPerfLevel(cDeviceId, cDpmMaxLevel)
	runtime.KeepAlive(cDpmMaxLevelAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetDpmIpMaxPerfLevel function as declared in MxSml.h
func mxSmlGetDpmIpMaxPerfLevel(DeviceId uint32, DpmIp MxSmlDpmIp, DpmMaxLevel *uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cDpmIp, cDpmIpAllocMap := (C.mxSmlDpmIp_t)(DpmIp), cgoAllocsUnknown
	cDpmMaxLevel, cDpmMaxLevelAllocMap := (*C.uint)(unsafe.Pointer(DpmMaxLevel)), cgoAllocsUnknown
	__ret := C.mxSmlGetDpmIpMaxPerfLevel(cDeviceId, cDpmIp, cDpmMaxLevel)
	runtime.KeepAlive(cDpmMaxLevelAllocMap)
	runtime.KeepAlive(cDpmIpAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlSetDpmIpMaxPerfLevel function as declared in MxSml.h
func mxSmlSetDpmIpMaxPerfLevel(DeviceId uint32, DpmIp MxSmlDpmIp, MaxPerfLevel uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cDpmIp, cDpmIpAllocMap := (C.mxSmlDpmIp_t)(DpmIp), cgoAllocsUnknown
	cMaxPerfLevel, cMaxPerfLevelAllocMap := (C.uint)(MaxPerfLevel), cgoAllocsUnknown
	__ret := C.mxSmlSetDpmIpMaxPerfLevel(cDeviceId, cDpmIp, cMaxPerfLevel)
	runtime.KeepAlive(cMaxPerfLevelAllocMap)
	runtime.KeepAlive(cDpmIpAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetMemoryInfo function as declared in MxSml.h
func mxSmlGetMemoryInfo(DeviceId uint32, MemoryInfo *MxSmlMemoryInfo) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cMemoryInfo, cMemoryInfoAllocMap := (*C.mxSmlMemoryInfo_t)(unsafe.Pointer(MemoryInfo)), cgoAllocsUnknown
	__ret := C.mxSmlGetMemoryInfo(cDeviceId, cMemoryInfo)
	runtime.KeepAlive(cMemoryInfoAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetEepromInfo function as declared in MxSml.h
func mxSmlGetEepromInfo(DeviceId uint32, EepromInfo *MxSmlEepromInfo) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cEepromInfo, cEepromInfoAllocMap := (*C.mxSmlEepromInfo_t)(unsafe.Pointer(EepromInfo)), cgoAllocsUnknown
	__ret := C.mxSmlGetEepromInfo(cDeviceId, cEepromInfo)
	runtime.KeepAlive(cEepromInfoAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetBoardSerial function as declared in MxSml.h
func mxSmlGetBoardSerial(DeviceId uint32, BoardSerial *byte, Size *uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cBoardSerial, cBoardSerialAllocMap := (*C.char)(unsafe.Pointer(BoardSerial)), cgoAllocsUnknown
	cSize, cSizeAllocMap := (*C.uint)(unsafe.Pointer(Size)), cgoAllocsUnknown
	__ret := C.mxSmlGetBoardSerial(cDeviceId, cBoardSerial, cSize)
	runtime.KeepAlive(cSizeAllocMap)
	runtime.KeepAlive(cBoardSerialAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetPptableVersion function as declared in MxSml.h
func mxSmlGetPptableVersion(DeviceId uint32, Size uint32, Version *byte) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cSize, cSizeAllocMap := (C.uint)(Size), cgoAllocsUnknown
	cVersion, cVersionAllocMap := (*C.char)(unsafe.Pointer(Version)), cgoAllocsUnknown
	__ret := C.mxSmlGetPptableVersion(cDeviceId, cSize, cVersion)
	runtime.KeepAlive(cVersionAllocMap)
	runtime.KeepAlive(cSizeAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetRasErrorData function as declared in MxSml.h
func mxSmlGetRasErrorData(DeviceId uint32, RasErrorData *MxSmlRasErrorData) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cRasErrorData, cRasErrorDataAllocMap := (*C.mxSmlRasErrorData_t)(unsafe.Pointer(RasErrorData)), cgoAllocsUnknown
	__ret := C.mxSmlGetRasErrorData(cDeviceId, cRasErrorData)
	runtime.KeepAlive(cRasErrorDataAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetRasErrorData_v2 function as declared in MxSml.h
func mxSmlGetRasErrorData_v2(DeviceId uint32, RasErrorData *MxSmlRasErrorData_v2) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cRasErrorData, cRasErrorDataAllocMap := (*C.mxSmlRasErrorData_v2_t)(unsafe.Pointer(RasErrorData)), cgoAllocsUnknown
	__ret := C.mxSmlGetRasErrorData_v2(cDeviceId, cRasErrorData)
	runtime.KeepAlive(cRasErrorDataAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetRasStatusData function as declared in MxSml.h
func mxSmlGetRasStatusData(DeviceId uint32, RasStatusData *MxSmlRasStatusData) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cRasStatusData, cRasStatusDataAllocMap := (*C.mxSmlRasStatusData_t)(unsafe.Pointer(RasStatusData)), cgoAllocsUnknown
	__ret := C.mxSmlGetRasStatusData(cDeviceId, cRasStatusData)
	runtime.KeepAlive(cRasStatusDataAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetPcieInfo function as declared in MxSml.h
func mxSmlGetPcieInfo(DeviceId uint32, PcieInfo *MxSmlPcieInfo) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cPcieInfo, cPcieInfoAllocMap := (*C.mxSmlPcieInfo_t)(unsafe.Pointer(PcieInfo)), cgoAllocsUnknown
	__ret := C.mxSmlGetPcieInfo(cDeviceId, cPcieInfo)
	runtime.KeepAlive(cPcieInfoAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetPcieMaxLinkInfo function as declared in MxSml.h
func mxSmlGetPcieMaxLinkInfo(DeviceId uint32, PcieMaxLinkInfo *MxSmlPcieInfo) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cPcieMaxLinkInfo, cPcieMaxLinkInfoAllocMap := (*C.mxSmlPcieInfo_t)(unsafe.Pointer(PcieMaxLinkInfo)), cgoAllocsUnknown
	__ret := C.mxSmlGetPcieMaxLinkInfo(cDeviceId, cPcieMaxLinkInfo)
	runtime.KeepAlive(cPcieMaxLinkInfoAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetPowerStateInfo function as declared in MxSml.h
func mxSmlGetPowerStateInfo(DeviceId uint32, DpmIp MxSmlDpmIp, PowerState *int32, Size *uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cDpmIp, cDpmIpAllocMap := (C.mxSmlDpmIp_t)(DpmIp), cgoAllocsUnknown
	cPowerState, cPowerStateAllocMap := (*C.int)(unsafe.Pointer(PowerState)), cgoAllocsUnknown
	cSize, cSizeAllocMap := (*C.uint)(unsafe.Pointer(Size)), cgoAllocsUnknown
	__ret := C.mxSmlGetPowerStateInfo(cDeviceId, cDpmIp, cPowerState, cSize)
	runtime.KeepAlive(cSizeAllocMap)
	runtime.KeepAlive(cPowerStateAllocMap)
	runtime.KeepAlive(cDpmIpAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetPciPowerState function as declared in MxSml.h
func mxSmlGetPciPowerState(DeviceId uint32, PciPowerState *MxSmlPciPowerState) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cPciPowerState, cPciPowerStateAllocMap := (*C.mxSmlPciPowerState_t)(unsafe.Pointer(PciPowerState)), cgoAllocsUnknown
	__ret := C.mxSmlGetPciPowerState(cDeviceId, cPciPowerState)
	runtime.KeepAlive(cPciPowerStateAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetVpuStatus function as declared in MxSml.h
func mxSmlGetVpuStatus(DeviceId uint32, VpuStatus *MxSmlVpuStatus) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cVpuStatus, cVpuStatusAllocMap := (*C.mxSmlVpuStatus_t)(unsafe.Pointer(VpuStatus)), cgoAllocsUnknown
	__ret := C.mxSmlGetVpuStatus(cDeviceId, cVpuStatus)
	runtime.KeepAlive(cVpuStatusAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetCodecStatus function as declared in MxSml.h
func mxSmlGetCodecStatus(DeviceId uint32, CodecStatus *MxSmlCodecStatus) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cCodecStatus, cCodecStatusAllocMap := (*C.mxSmlCodecStatus_t)(unsafe.Pointer(CodecStatus)), cgoAllocsUnknown
	__ret := C.mxSmlGetCodecStatus(cDeviceId, cCodecStatus)
	runtime.KeepAlive(cCodecStatusAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetClocks function as declared in MxSml.h
func mxSmlGetClocks(DeviceId uint32, ClockIp MxSmlClockIp, ClocksSize *uint32, ClocksMhz *uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cClockIp, cClockIpAllocMap := (C.mxSmlClockIp_t)(ClockIp), cgoAllocsUnknown
	cClocksSize, cClocksSizeAllocMap := (*C.uint)(unsafe.Pointer(ClocksSize)), cgoAllocsUnknown
	cClocksMhz, cClocksMhzAllocMap := (*C.uint)(unsafe.Pointer(ClocksMhz)), cgoAllocsUnknown
	__ret := C.mxSmlGetClocks(cDeviceId, cClockIp, cClocksSize, cClocksMhz)
	runtime.KeepAlive(cClocksMhzAllocMap)
	runtime.KeepAlive(cClocksSizeAllocMap)
	runtime.KeepAlive(cClockIpAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetHbmBandWidth function as declared in MxSml.h
func mxSmlGetHbmBandWidth(DeviceId uint32, HbmBandWidth *MxSmlHbmBandWidth) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cHbmBandWidth, cHbmBandWidthAllocMap := (*C.mxSmlHbmBandWidth_t)(unsafe.Pointer(HbmBandWidth)), cgoAllocsUnknown
	__ret := C.mxSmlGetHbmBandWidth(cDeviceId, cHbmBandWidth)
	runtime.KeepAlive(cHbmBandWidthAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetPcieThroughput function as declared in MxSml.h
func mxSmlGetPcieThroughput(DeviceId uint32, PcieThroughput *MxSmlPcieThroughput) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cPcieThroughput, cPcieThroughputAllocMap := (*C.mxSmlPcieThroughput_t)(unsafe.Pointer(PcieThroughput)), cgoAllocsUnknown
	__ret := C.mxSmlGetPcieThroughput(cDeviceId, cPcieThroughput)
	runtime.KeepAlive(cPcieThroughputAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetDmaBandwidth function as declared in MxSml.h
func mxSmlGetDmaBandwidth(DeviceId uint32, DmaBandwidth *MxSmlDmaEngineBandwidth, Size *uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cDmaBandwidth, cDmaBandwidthAllocMap := (*C.mxSmlDmaEngineBandwidth_t)(unsafe.Pointer(DmaBandwidth)), cgoAllocsUnknown
	cSize, cSizeAllocMap := (*C.uint)(unsafe.Pointer(Size)), cgoAllocsUnknown
	__ret := C.mxSmlGetDmaBandwidth(cDeviceId, cDmaBandwidth, cSize)
	runtime.KeepAlive(cSizeAllocMap)
	runtime.KeepAlive(cDmaBandwidthAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetMetaXLinkInfo function as declared in MxSml.h
func mxSmlGetMetaXLinkInfo(DeviceId uint32, MetaxLinkInfo *MxSmlMetaXLinkInfo) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cMetaxLinkInfo, cMetaxLinkInfoAllocMap := (*C.mxSmlMetaXLinkInfo_t)(unsafe.Pointer(MetaxLinkInfo)), cgoAllocsUnknown
	__ret := C.mxSmlGetMetaXLinkInfo(cDeviceId, cMetaxLinkInfo)
	runtime.KeepAlive(cMetaxLinkInfoAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetMetaXLinkInfo_v2 function as declared in MxSml.h
func mxSmlGetMetaXLinkInfo_v2(DeviceId uint32, LinkSize *uint32, MxlkInfos *MxSmlSingleMxlkInfo) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cLinkSize, cLinkSizeAllocMap := (*C.uint)(unsafe.Pointer(LinkSize)), cgoAllocsUnknown
	cMxlkInfos, cMxlkInfosAllocMap := (*C.mxSmlSingleMxlkInfo_t)(unsafe.Pointer(MxlkInfos)), cgoAllocsUnknown
	__ret := C.mxSmlGetMetaXLinkInfo_v2(cDeviceId, cLinkSize, cMxlkInfos)
	runtime.KeepAlive(cMxlkInfosAllocMap)
	runtime.KeepAlive(cLinkSizeAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetMetaXLinkBandwidth function as declared in MxSml.h
func mxSmlGetMetaXLinkBandwidth(DeviceId uint32, _type MxSmlMetaXLinkType, LinkSize *uint32, MetaxLinkBandwidth *MxSmlMetaXLinkBandwidth) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	c_type, c_typeAllocMap := (C.mxSmlMetaXLinkType_t)(_type), cgoAllocsUnknown
	cLinkSize, cLinkSizeAllocMap := (*C.uint)(unsafe.Pointer(LinkSize)), cgoAllocsUnknown
	cMetaxLinkBandwidth, cMetaxLinkBandwidthAllocMap := (*C.mxSmlMetaXLinkBandwidth_t)(unsafe.Pointer(MetaxLinkBandwidth)), cgoAllocsUnknown
	__ret := C.mxSmlGetMetaXLinkBandwidth(cDeviceId, c_type, cLinkSize, cMetaxLinkBandwidth)
	runtime.KeepAlive(cMetaxLinkBandwidthAllocMap)
	runtime.KeepAlive(cLinkSizeAllocMap)
	runtime.KeepAlive(c_typeAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetMetaXLinkTrafficStat function as declared in MxSml.h
func mxSmlGetMetaXLinkTrafficStat(DeviceId uint32, _type MxSmlMetaXLinkType, LinkSize *uint32, MetaxLinkTrafficStat *MxSmlMetaXLinkTrafficStat) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	c_type, c_typeAllocMap := (C.mxSmlMetaXLinkType_t)(_type), cgoAllocsUnknown
	cLinkSize, cLinkSizeAllocMap := (*C.uint)(unsafe.Pointer(LinkSize)), cgoAllocsUnknown
	cMetaxLinkTrafficStat, cMetaxLinkTrafficStatAllocMap := (*C.mxSmlMetaXLinkTrafficStat_t)(unsafe.Pointer(MetaxLinkTrafficStat)), cgoAllocsUnknown
	__ret := C.mxSmlGetMetaXLinkTrafficStat(cDeviceId, c_type, cLinkSize, cMetaxLinkTrafficStat)
	runtime.KeepAlive(cMetaxLinkTrafficStatAllocMap)
	runtime.KeepAlive(cLinkSizeAllocMap)
	runtime.KeepAlive(c_typeAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetMetaXLinkAer function as declared in MxSml.h
func mxSmlGetMetaXLinkAer(DeviceId uint32, LinkSize *uint32, MetaxLinkAer *MxSmlMetaXLinkAer) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cLinkSize, cLinkSizeAllocMap := (*C.uint)(unsafe.Pointer(LinkSize)), cgoAllocsUnknown
	cMetaxLinkAer, cMetaxLinkAerAllocMap := (*C.mxSmlMetaXLinkAer_t)(unsafe.Pointer(MetaxLinkAer)), cgoAllocsUnknown
	__ret := C.mxSmlGetMetaXLinkAer(cDeviceId, cLinkSize, cMetaxLinkAer)
	runtime.KeepAlive(cMetaxLinkAerAllocMap)
	runtime.KeepAlive(cLinkSizeAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetMetaXLinkRemoteInfo function as declared in MxSml.h
func mxSmlGetMetaXLinkRemoteInfo(DeviceId uint32, LinkId uint32, Remote *MxSmlMetaXLinkRemoteInfo) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cLinkId, cLinkIdAllocMap := (C.uint)(LinkId), cgoAllocsUnknown
	cRemote, cRemoteAllocMap := (*C.mxSmlMetaXLinkRemoteInfo_t)(unsafe.Pointer(Remote)), cgoAllocsUnknown
	__ret := C.mxSmlGetMetaXLinkRemoteInfo(cDeviceId, cLinkId, cRemote)
	runtime.KeepAlive(cRemoteAllocMap)
	runtime.KeepAlive(cLinkIdAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetMetaXLinkState function as declared in MxSml.h
func mxSmlGetMetaXLinkState(DeviceId uint32, MxlkStateCode *MxSmlMetaXLinkState, MxlkState *byte, Size *uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cMxlkStateCode, cMxlkStateCodeAllocMap := (*C.mxSmlMetaXLinkState_t)(unsafe.Pointer(MxlkStateCode)), cgoAllocsUnknown
	cMxlkState, cMxlkStateAllocMap := (*C.char)(unsafe.Pointer(MxlkState)), cgoAllocsUnknown
	cSize, cSizeAllocMap := (*C.uint)(unsafe.Pointer(Size)), cgoAllocsUnknown
	__ret := C.mxSmlGetMetaXLinkState(cDeviceId, cMxlkStateCode, cMxlkState, cSize)
	runtime.KeepAlive(cSizeAllocMap)
	runtime.KeepAlive(cMxlkStateAllocMap)
	runtime.KeepAlive(cMxlkStateCodeAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetMetaXLinkPortState function as declared in MxSml.h
func mxSmlGetMetaXLinkPortState(DeviceId uint32, MxlkPortState *MxSmlMxlkPortState, Size *uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cMxlkPortState, cMxlkPortStateAllocMap := (*C.mxSmlMxlkPortState_t)(unsafe.Pointer(MxlkPortState)), cgoAllocsUnknown
	cSize, cSizeAllocMap := (*C.uint)(unsafe.Pointer(Size)), cgoAllocsUnknown
	__ret := C.mxSmlGetMetaXLinkPortState(cDeviceId, cMxlkPortState, cSize)
	runtime.KeepAlive(cSizeAllocMap)
	runtime.KeepAlive(cMxlkPortStateAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlSetMetaXLinkState function as declared in MxSml.h
func mxSmlSetMetaXLinkState(DeviceId uint32, MxlkState uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cMxlkState, cMxlkStateAllocMap := (C.uint)(MxlkState), cgoAllocsUnknown
	__ret := C.mxSmlSetMetaXLinkState(cDeviceId, cMxlkState)
	runtime.KeepAlive(cMxlkStateAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetMetaXLinkTopo function as declared in MxSml.h
func mxSmlGetMetaXLinkTopo(DeviceId uint32, MetaxLinkTopo *MxSmlMetaXLinkTopo) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cMetaxLinkTopo, cMetaxLinkTopoAllocMap := (*C.mxSmlMetaXLinkTopo_t)(unsafe.Pointer(MetaxLinkTopo)), cgoAllocsUnknown
	__ret := C.mxSmlGetMetaXLinkTopo(cDeviceId, cMetaxLinkTopo)
	runtime.KeepAlive(cMetaxLinkTopoAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlVbiosUpgrade function as declared in MxSml.h
func mxSmlVbiosUpgrade(DeviceId uint32, VbiosUpgradeArg *MxSmlVbiosUpgradeArg) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cVbiosUpgradeArg, cVbiosUpgradeArgAllocMap := (*C.mxSmlVbiosUpgradeArg_t)(unsafe.Pointer(VbiosUpgradeArg)), cgoAllocsUnknown
	__ret := C.mxSmlVbiosUpgrade(cDeviceId, cVbiosUpgradeArg)
	runtime.KeepAlive(cVbiosUpgradeArgAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlDumpVbios function as declared in MxSml.h
func mxSmlDumpVbios(DeviceId uint32, TimeLimit uint32, BinPath string, Ret *uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cTimeLimit, cTimeLimitAllocMap := (C.uint)(TimeLimit), cgoAllocsUnknown
	cBinPath, cBinPathAllocMap := unpackPCharString(BinPath)
	cRet, cRetAllocMap := (*C.uint)(unsafe.Pointer(Ret)), cgoAllocsUnknown
	__ret := C.mxSmlDumpVbios(cDeviceId, cTimeLimit, cBinPath, cRet)
	runtime.KeepAlive(cRetAllocMap)
	runtime.KeepAlive(cBinPathAllocMap)
	runtime.KeepAlive(cTimeLimitAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlFunctionLevelReset function as declared in MxSml.h
func mxSmlFunctionLevelReset(DeviceId uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	__ret := C.mxSmlFunctionLevelReset(cDeviceId)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlFunctionLevelResetVfFromPf function as declared in MxSml.h
func mxSmlFunctionLevelResetVfFromPf(DeviceId uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	__ret := C.mxSmlFunctionLevelResetVfFromPf(cDeviceId)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlSetUnlockKey function as declared in MxSml.h
func mxSmlSetUnlockKey(DeviceId uint32, UnlockKey string) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cUnlockKey, cUnlockKeyAllocMap := unpackPCharString(UnlockKey)
	__ret := C.mxSmlSetUnlockKey(cDeviceId, cUnlockKey)
	runtime.KeepAlive(cUnlockKeyAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetProcessInfo function as declared in MxSml.h
func mxSmlGetProcessInfo(ProcessNumber uint32, ProcessInfo *MxSmlProcessInfo) MxSmlReturn {
	cProcessNumber, cProcessNumberAllocMap := (C.uint)(ProcessNumber), cgoAllocsUnknown
	cProcessInfo, cProcessInfoAllocMap := (*C.mxSmlProcessInfo_t)(unsafe.Pointer(ProcessInfo)), cgoAllocsUnknown
	__ret := C.mxSmlGetProcessInfo(cProcessNumber, cProcessInfo)
	runtime.KeepAlive(cProcessInfoAllocMap)
	runtime.KeepAlive(cProcessNumberAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetProcessInfo_v2 function as declared in MxSml.h
func mxSmlGetProcessInfo_v2(ProcessNumber uint32, ProcessInfo *MxSmlProcessInfo_v2) MxSmlReturn {
	cProcessNumber, cProcessNumberAllocMap := (C.uint)(ProcessNumber), cgoAllocsUnknown
	cProcessInfo, cProcessInfoAllocMap := (*C.mxSmlProcessInfo_v2_t)(unsafe.Pointer(ProcessInfo)), cgoAllocsUnknown
	__ret := C.mxSmlGetProcessInfo_v2(cProcessNumber, cProcessInfo)
	runtime.KeepAlive(cProcessInfoAllocMap)
	runtime.KeepAlive(cProcessNumberAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetProcessInfo_v3 function as declared in MxSml.h
func mxSmlGetProcessInfo_v3(ProcessNumber uint32, ProcessInfo *MxSmlProcessInfo_v3) MxSmlReturn {
	cProcessNumber, cProcessNumberAllocMap := (C.uint)(ProcessNumber), cgoAllocsUnknown
	cProcessInfo, cProcessInfoAllocMap := (*C.mxSmlProcessInfo_v3_t)(unsafe.Pointer(ProcessInfo)), cgoAllocsUnknown
	__ret := C.mxSmlGetProcessInfo_v3(cProcessNumber, cProcessInfo)
	runtime.KeepAlive(cProcessInfoAllocMap)
	runtime.KeepAlive(cProcessNumberAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetNumberOfProcess function as declared in MxSml.h
func mxSmlGetNumberOfProcess(ProcessNumber *uint32) MxSmlReturn {
	cProcessNumber, cProcessNumberAllocMap := (*C.uint)(unsafe.Pointer(ProcessNumber)), cgoAllocsUnknown
	__ret := C.mxSmlGetNumberOfProcess(cProcessNumber)
	runtime.KeepAlive(cProcessNumberAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetSingleGpuProcess function as declared in MxSml.h
func mxSmlGetSingleGpuProcess(DeviceId uint32, ProcessNumber *uint32, ProcessInfo *MxSmlProcessInfo) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cProcessNumber, cProcessNumberAllocMap := (*C.uint)(unsafe.Pointer(ProcessNumber)), cgoAllocsUnknown
	cProcessInfo, cProcessInfoAllocMap := (*C.mxSmlProcessInfo_t)(unsafe.Pointer(ProcessInfo)), cgoAllocsUnknown
	__ret := C.mxSmlGetSingleGpuProcess(cDeviceId, cProcessNumber, cProcessInfo)
	runtime.KeepAlive(cProcessInfoAllocMap)
	runtime.KeepAlive(cProcessNumberAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetSingleGpuProcess_v2 function as declared in MxSml.h
func mxSmlGetSingleGpuProcess_v2(DeviceId uint32, ProcessNumber *uint32, ProcessInfo *MxSmlProcessInfo_v2) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cProcessNumber, cProcessNumberAllocMap := (*C.uint)(unsafe.Pointer(ProcessNumber)), cgoAllocsUnknown
	cProcessInfo, cProcessInfoAllocMap := (*C.mxSmlProcessInfo_v2_t)(unsafe.Pointer(ProcessInfo)), cgoAllocsUnknown
	__ret := C.mxSmlGetSingleGpuProcess_v2(cDeviceId, cProcessNumber, cProcessInfo)
	runtime.KeepAlive(cProcessInfoAllocMap)
	runtime.KeepAlive(cProcessNumberAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetSingleGpuProcess_v3 function as declared in MxSml.h
func mxSmlGetSingleGpuProcess_v3(DeviceId uint32, ProcessNumber *uint32, ProcessInfo *MxSmlProcessInfo_v3) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cProcessNumber, cProcessNumberAllocMap := (*C.uint)(unsafe.Pointer(ProcessNumber)), cgoAllocsUnknown
	cProcessInfo, cProcessInfoAllocMap := (*C.mxSmlProcessInfo_v3_t)(unsafe.Pointer(ProcessInfo)), cgoAllocsUnknown
	__ret := C.mxSmlGetSingleGpuProcess_v3(cDeviceId, cProcessNumber, cProcessInfo)
	runtime.KeepAlive(cProcessInfoAllocMap)
	runtime.KeepAlive(cProcessNumberAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetDeviceTopology function as declared in MxSml.h
func mxSmlGetDeviceTopology(DeviceId1 uint32, DeviceId2 uint32, TopoInfo *MxSmlGpuTopologyLevel) MxSmlReturn {
	cDeviceId1, cDeviceId1AllocMap := (C.uint)(DeviceId1), cgoAllocsUnknown
	cDeviceId2, cDeviceId2AllocMap := (C.uint)(DeviceId2), cgoAllocsUnknown
	cTopoInfo, cTopoInfoAllocMap := (*C.mxSmlGpuTopologyLevel_t)(unsafe.Pointer(TopoInfo)), cgoAllocsUnknown
	__ret := C.mxSmlGetDeviceTopology(cDeviceId1, cDeviceId2, cTopoInfo)
	runtime.KeepAlive(cTopoInfoAllocMap)
	runtime.KeepAlive(cDeviceId2AllocMap)
	runtime.KeepAlive(cDeviceId1AllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetDeviceDistance function as declared in MxSml.h
func mxSmlGetDeviceDistance(DeviceId1 uint32, DeviceId2 uint32, Distance *uint32) MxSmlReturn {
	cDeviceId1, cDeviceId1AllocMap := (C.uint)(DeviceId1), cgoAllocsUnknown
	cDeviceId2, cDeviceId2AllocMap := (C.uint)(DeviceId2), cgoAllocsUnknown
	cDistance, cDistanceAllocMap := (*C.uint)(unsafe.Pointer(Distance)), cgoAllocsUnknown
	__ret := C.mxSmlGetDeviceDistance(cDeviceId1, cDeviceId2, cDistance)
	runtime.KeepAlive(cDistanceAllocMap)
	runtime.KeepAlive(cDeviceId2AllocMap)
	runtime.KeepAlive(cDeviceId1AllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetCpuAffinity function as declared in MxSml.h
func mxSmlGetCpuAffinity(DeviceId uint32, CpuSetSize uint32, CpuSet *uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cCpuSetSize, cCpuSetSizeAllocMap := (C.uint)(CpuSetSize), cgoAllocsUnknown
	cCpuSet, cCpuSetAllocMap := (*C.uint)(unsafe.Pointer(CpuSet)), cgoAllocsUnknown
	__ret := C.mxSmlGetCpuAffinity(cDeviceId, cCpuSetSize, cCpuSet)
	runtime.KeepAlive(cCpuSetAllocMap)
	runtime.KeepAlive(cCpuSetSizeAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlSetCpuAffinity function as declared in MxSml.h
func mxSmlSetCpuAffinity(DeviceId uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	__ret := C.mxSmlSetCpuAffinity(cDeviceId)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlClearCpuAffinity function as declared in MxSml.h
func mxSmlClearCpuAffinity(DeviceId uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	__ret := C.mxSmlClearCpuAffinity(cDeviceId)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetNodeAffinity function as declared in MxSml.h
func mxSmlGetNodeAffinity(DeviceId uint32, NodeSetSize uint32, NodeSet *uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cNodeSetSize, cNodeSetSizeAllocMap := (C.uint)(NodeSetSize), cgoAllocsUnknown
	cNodeSet, cNodeSetAllocMap := (*C.uint)(unsafe.Pointer(NodeSet)), cgoAllocsUnknown
	__ret := C.mxSmlGetNodeAffinity(cDeviceId, cNodeSetSize, cNodeSet)
	runtime.KeepAlive(cNodeSetAllocMap)
	runtime.KeepAlive(cNodeSetSizeAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlReset function as declared in MxSml.h
func mxSmlReset(DeviceId uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	__ret := C.mxSmlReset(cDeviceId)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlForceReset function as declared in MxSml.h
func mxSmlForceReset(DeviceId uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	__ret := C.mxSmlForceReset(cDeviceId)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlSetPciSpeed function as declared in MxSml.h
func mxSmlSetPciSpeed(DeviceId uint32, PciGen MxSmlPciGen) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cPciGen, cPciGenAllocMap := (C.mxSmlPciGen_t)(PciGen), cgoAllocsUnknown
	__ret := C.mxSmlSetPciSpeed(cDeviceId, cPciGen)
	runtime.KeepAlive(cPciGenAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetPciDelay function as declared in MxSml.h
func mxSmlGetPciDelay(DeviceId uint32, PciDelay *uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cPciDelay, cPciDelayAllocMap := (*C.uint)(unsafe.Pointer(PciDelay)), cgoAllocsUnknown
	__ret := C.mxSmlGetPciDelay(cDeviceId, cPciDelay)
	runtime.KeepAlive(cPciDelayAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlSetPciDelay function as declared in MxSml.h
func mxSmlSetPciDelay(DeviceId uint32, PciDelay uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cPciDelay, cPciDelayAllocMap := (C.uint)(PciDelay), cgoAllocsUnknown
	__ret := C.mxSmlSetPciDelay(cDeviceId, cPciDelay)
	runtime.KeepAlive(cPciDelayAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetDpmIpClockInfo function as declared in MxSml.h
func mxSmlGetDpmIpClockInfo(DeviceId uint32, DpmIp MxSmlDpmIp, ClockInfo *uint32, Size *uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cDpmIp, cDpmIpAllocMap := (C.mxSmlDpmIp_t)(DpmIp), cgoAllocsUnknown
	cClockInfo, cClockInfoAllocMap := (*C.uint)(unsafe.Pointer(ClockInfo)), cgoAllocsUnknown
	cSize, cSizeAllocMap := (*C.uint)(unsafe.Pointer(Size)), cgoAllocsUnknown
	__ret := C.mxSmlGetDpmIpClockInfo(cDeviceId, cDpmIp, cClockInfo, cSize)
	runtime.KeepAlive(cSizeAllocMap)
	runtime.KeepAlive(cClockInfoAllocMap)
	runtime.KeepAlive(cDpmIpAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetDpmIpVddInfo function as declared in MxSml.h
func mxSmlGetDpmIpVddInfo(DeviceId uint32, DpmIp MxSmlDpmIp, VoltageInfo *uint32, Size *uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cDpmIp, cDpmIpAllocMap := (C.mxSmlDpmIp_t)(DpmIp), cgoAllocsUnknown
	cVoltageInfo, cVoltageInfoAllocMap := (*C.uint)(unsafe.Pointer(VoltageInfo)), cgoAllocsUnknown
	cSize, cSizeAllocMap := (*C.uint)(unsafe.Pointer(Size)), cgoAllocsUnknown
	__ret := C.mxSmlGetDpmIpVddInfo(cDeviceId, cDpmIp, cVoltageInfo, cSize)
	runtime.KeepAlive(cSizeAllocMap)
	runtime.KeepAlive(cVoltageInfoAllocMap)
	runtime.KeepAlive(cDpmIpAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetCurrentDpmIpPerfLevel function as declared in MxSml.h
func mxSmlGetCurrentDpmIpPerfLevel(DeviceId uint32, DpmIp MxSmlDpmIp, DpmIpPerfLevel *uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cDpmIp, cDpmIpAllocMap := (C.mxSmlDpmIp_t)(DpmIp), cgoAllocsUnknown
	cDpmIpPerfLevel, cDpmIpPerfLevelAllocMap := (*C.uint)(unsafe.Pointer(DpmIpPerfLevel)), cgoAllocsUnknown
	__ret := C.mxSmlGetCurrentDpmIpPerfLevel(cDeviceId, cDpmIp, cDpmIpPerfLevel)
	runtime.KeepAlive(cDpmIpPerfLevelAllocMap)
	runtime.KeepAlive(cDpmIpAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetMacaVersion function as declared in MxSml.h
func mxSmlGetMacaVersion(Version *byte, Size *uint32) MxSmlReturn {
	cVersion, cVersionAllocMap := (*C.char)(unsafe.Pointer(Version)), cgoAllocsUnknown
	cSize, cSizeAllocMap := (*C.uint)(unsafe.Pointer(Size)), cgoAllocsUnknown
	__ret := C.mxSmlGetMacaVersion(cVersion, cSize)
	runtime.KeepAlive(cSizeAllocMap)
	runtime.KeepAlive(cVersionAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetDeviceVersion function as declared in MxSml.h
func mxSmlGetDeviceVersion(DeviceId uint32, VersionUnit MxSmlVersionUnit, Version *byte, Size *uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cVersionUnit, cVersionUnitAllocMap := (C.mxSmlVersionUnit_t)(VersionUnit), cgoAllocsUnknown
	cVersion, cVersionAllocMap := (*C.char)(unsafe.Pointer(Version)), cgoAllocsUnknown
	cSize, cSizeAllocMap := (*C.uint)(unsafe.Pointer(Size)), cgoAllocsUnknown
	__ret := C.mxSmlGetDeviceVersion(cDeviceId, cVersionUnit, cVersion, cSize)
	runtime.KeepAlive(cSizeAllocMap)
	runtime.KeepAlive(cVersionAllocMap)
	runtime.KeepAlive(cVersionUnitAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetDeviceIpUsage function as declared in MxSml.h
func mxSmlGetDeviceIpUsage(DeviceId uint32, Ip MxSmlUsageIp, Usage *int32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cIp, cIpAllocMap := (C.mxSmlUsageIp_t)(Ip), cgoAllocsUnknown
	cUsage, cUsageAllocMap := (*C.int)(unsafe.Pointer(Usage)), cgoAllocsUnknown
	__ret := C.mxSmlGetDeviceIpUsage(cDeviceId, cIp, cUsage)
	runtime.KeepAlive(cUsageAllocMap)
	runtime.KeepAlive(cIpAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetXcoreApUsage function as declared in MxSml.h
func mxSmlGetXcoreApUsage(DeviceId uint32, ApUsage *uint32, Size *uint32, DpcNum *uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cApUsage, cApUsageAllocMap := (*C.uint)(unsafe.Pointer(ApUsage)), cgoAllocsUnknown
	cSize, cSizeAllocMap := (*C.uint)(unsafe.Pointer(Size)), cgoAllocsUnknown
	cDpcNum, cDpcNumAllocMap := (*C.uint)(unsafe.Pointer(DpcNum)), cgoAllocsUnknown
	__ret := C.mxSmlGetXcoreApUsage(cDeviceId, cApUsage, cSize, cDpcNum)
	runtime.KeepAlive(cDpcNumAllocMap)
	runtime.KeepAlive(cSizeAllocMap)
	runtime.KeepAlive(cApUsageAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetFwIpLoglevel function as declared in MxSml.h
func mxSmlGetFwIpLoglevel(DeviceId uint32, FwIpName MxSmlFwIpName, FwIpLoglevel *MxSmlLoglevel) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cFwIpName, cFwIpNameAllocMap := (C.mxSmlFwIpName_t)(FwIpName), cgoAllocsUnknown
	cFwIpLoglevel, cFwIpLoglevelAllocMap := (*C.mxSmlLoglevel_t)(unsafe.Pointer(FwIpLoglevel)), cgoAllocsUnknown
	__ret := C.mxSmlGetFwIpLoglevel(cDeviceId, cFwIpName, cFwIpLoglevel)
	runtime.KeepAlive(cFwIpLoglevelAllocMap)
	runtime.KeepAlive(cFwIpNameAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlSetFwLoglevel function as declared in MxSml.h
func mxSmlSetFwLoglevel(DeviceId uint32, FwIpName MxSmlFwIpName, Loglevel MxSmlLoglevel) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cFwIpName, cFwIpNameAllocMap := (C.mxSmlFwIpName_t)(FwIpName), cgoAllocsUnknown
	cLoglevel, cLoglevelAllocMap := (C.mxSmlLoglevel_t)(Loglevel), cgoAllocsUnknown
	__ret := C.mxSmlSetFwLoglevel(cDeviceId, cFwIpName, cLoglevel)
	runtime.KeepAlive(cLoglevelAllocMap)
	runtime.KeepAlive(cFwIpNameAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetChipSerial function as declared in MxSml.h
func mxSmlGetChipSerial(DeviceId uint32, ChipSerial *byte, Size *uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cChipSerial, cChipSerialAllocMap := (*C.char)(unsafe.Pointer(ChipSerial)), cgoAllocsUnknown
	cSize, cSizeAllocMap := (*C.uint)(unsafe.Pointer(Size)), cgoAllocsUnknown
	__ret := C.mxSmlGetChipSerial(cDeviceId, cChipSerial, cSize)
	runtime.KeepAlive(cSizeAllocMap)
	runtime.KeepAlive(cChipSerialAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetApUsageToggle function as declared in MxSml.h
func mxSmlGetApUsageToggle(DeviceId uint32, ApUsageToggle *uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cApUsageToggle, cApUsageToggleAllocMap := (*C.uint)(unsafe.Pointer(ApUsageToggle)), cgoAllocsUnknown
	__ret := C.mxSmlGetApUsageToggle(cDeviceId, cApUsageToggle)
	runtime.KeepAlive(cApUsageToggleAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlSetApUsageToggle function as declared in MxSml.h
func mxSmlSetApUsageToggle(DeviceId uint32, Toggle int32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cToggle, cToggleAllocMap := (C.int)(Toggle), cgoAllocsUnknown
	__ret := C.mxSmlSetApUsageToggle(cDeviceId, cToggle)
	runtime.KeepAlive(cToggleAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetEccState function as declared in MxSml.h
func mxSmlGetEccState(DeviceId uint32, EccState *uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cEccState, cEccStateAllocMap := (*C.uint)(unsafe.Pointer(EccState)), cgoAllocsUnknown
	__ret := C.mxSmlGetEccState(cDeviceId, cEccState)
	runtime.KeepAlive(cEccStateAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlSetEccState function as declared in MxSml.h
func mxSmlSetEccState(DeviceId uint32, EccState uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cEccState, cEccStateAllocMap := (C.uint)(EccState), cgoAllocsUnknown
	__ret := C.mxSmlSetEccState(cDeviceId, cEccState)
	runtime.KeepAlive(cEccStateAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetFwLoglevel function as declared in MxSml.h
func mxSmlGetFwLoglevel(DeviceId uint32, FwLoglevel *MxSmlFwLoglevel) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cFwLoglevel, cFwLoglevelAllocMap := (*C.mxSmlFwLoglevel_t)(unsafe.Pointer(FwLoglevel)), cgoAllocsUnknown
	__ret := C.mxSmlGetFwLoglevel(cDeviceId, cFwLoglevel)
	runtime.KeepAlive(cFwLoglevelAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetSriovState function as declared in MxSml.h
func mxSmlGetSriovState(DeviceId uint32, SriovState *uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cSriovState, cSriovStateAllocMap := (*C.uint)(unsafe.Pointer(SriovState)), cgoAllocsUnknown
	__ret := C.mxSmlGetSriovState(cDeviceId, cSriovState)
	runtime.KeepAlive(cSriovStateAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetDeviceSlot function as declared in MxSml.h
func mxSmlGetDeviceSlot(DeviceId uint32, SlotId *uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cSlotId, cSlotIdAllocMap := (*C.uint)(unsafe.Pointer(SlotId)), cgoAllocsUnknown
	__ret := C.mxSmlGetDeviceSlot(cDeviceId, cSlotId)
	runtime.KeepAlive(cSlotIdAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetOpticalModuleStatus function as declared in MxSml.h
func mxSmlGetOpticalModuleStatus(DeviceId uint32, Status *MxSmlOpticalModuleStatus, Size *uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cStatus, cStatusAllocMap := (*C.mxSmlOpticalModuleStatus_t)(unsafe.Pointer(Status)), cgoAllocsUnknown
	cSize, cSizeAllocMap := (*C.uint)(unsafe.Pointer(Size)), cgoAllocsUnknown
	__ret := C.mxSmlGetOpticalModuleStatus(cDeviceId, cStatus, cSize)
	runtime.KeepAlive(cSizeAllocMap)
	runtime.KeepAlive(cStatusAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetOpticalModuleInfo function as declared in MxSml.h
func mxSmlGetOpticalModuleInfo(DeviceId uint32, Info *MxSmlOpticalModuleInfo, Size *uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cInfo, cInfoAllocMap := (*C.mxSmlOpticalModuleInfo_t)(unsafe.Pointer(Info)), cgoAllocsUnknown
	cSize, cSizeAllocMap := (*C.uint)(unsafe.Pointer(Size)), cgoAllocsUnknown
	__ret := C.mxSmlGetOpticalModuleInfo(cDeviceId, cInfo, cSize)
	runtime.KeepAlive(cSizeAllocMap)
	runtime.KeepAlive(cInfoAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetOpticalModulePower function as declared in MxSml.h
func mxSmlGetOpticalModulePower(DeviceId uint32, Power *MxSmlOpticalModulePower, Size *uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cPower, cPowerAllocMap := (*C.mxSmlOpticalModulePower_t)(unsafe.Pointer(Power)), cgoAllocsUnknown
	cSize, cSizeAllocMap := (*C.uint)(unsafe.Pointer(Size)), cgoAllocsUnknown
	__ret := C.mxSmlGetOpticalModulePower(cDeviceId, cPower, cSize)
	runtime.KeepAlive(cSizeAllocMap)
	runtime.KeepAlive(cPowerAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetDeviceRealPath function as declared in MxSml.h
func mxSmlGetDeviceRealPath(DeviceId uint32, DeviceRealPath *byte, Size *uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cDeviceRealPath, cDeviceRealPathAllocMap := (*C.char)(unsafe.Pointer(DeviceRealPath)), cgoAllocsUnknown
	cSize, cSizeAllocMap := (*C.uint)(unsafe.Pointer(Size)), cgoAllocsUnknown
	__ret := C.mxSmlGetDeviceRealPath(cDeviceId, cDeviceRealPath, cSize)
	runtime.KeepAlive(cSizeAllocMap)
	runtime.KeepAlive(cDeviceRealPathAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetDeviceState function as declared in MxSml.h
func mxSmlGetDeviceState(DeviceId uint32, DeviceState *int32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cDeviceState, cDeviceStateAllocMap := (*C.int)(unsafe.Pointer(DeviceState)), cgoAllocsUnknown
	__ret := C.mxSmlGetDeviceState(cDeviceId, cDeviceState)
	runtime.KeepAlive(cDeviceStateAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetErrorString function as declared in MxSml.h
func mxSmlGetErrorString(Result MxSmlReturn) *byte {
	cResult, cResultAllocMap := (C.mxSmlReturn_t)(Result), cgoAllocsUnknown
	__ret := C.mxSmlGetErrorString(cResult)
	runtime.KeepAlive(cResultAllocMap)
	__v := *(**byte)(unsafe.Pointer(&__ret))
	return __v
}

// mxSmlGetOpMode function as declared in MxSml.h
func mxSmlGetOpMode(OpMode *uint32) MxSmlReturn {
	cOpMode, cOpModeAllocMap := (*C.uint)(unsafe.Pointer(OpMode)), cgoAllocsUnknown
	__ret := C.mxSmlGetOpMode(cOpMode)
	runtime.KeepAlive(cOpModeAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlSetOpMode function as declared in MxSml.h
func mxSmlSetOpMode(OpMode uint32) MxSmlReturn {
	cOpMode, cOpModeAllocMap := (C.uint)(OpMode), cgoAllocsUnknown
	__ret := C.mxSmlSetOpMode(cOpMode)
	runtime.KeepAlive(cOpModeAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetLocalAndRemoteUuid function as declared in MxSml.h
func mxSmlGetLocalAndRemoteUuid(Local *byte, Remote *byte, Size *uint32) MxSmlReturn {
	cLocal, cLocalAllocMap := (*C.char)(unsafe.Pointer(Local)), cgoAllocsUnknown
	cRemote, cRemoteAllocMap := (*C.char)(unsafe.Pointer(Remote)), cgoAllocsUnknown
	cSize, cSizeAllocMap := (*C.uint)(unsafe.Pointer(Size)), cgoAllocsUnknown
	__ret := C.mxSmlGetLocalAndRemoteUuid(cLocal, cRemote, cSize)
	runtime.KeepAlive(cSizeAllocMap)
	runtime.KeepAlive(cRemoteAllocMap)
	runtime.KeepAlive(cLocalAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetLocalAndMultipleRemoteUuid function as declared in MxSml.h
func mxSmlGetLocalAndMultipleRemoteUuid(Local *byte, Remotes []*byte, RemotesSize *uint32, UuidSize *uint32) MxSmlReturn {
	cLocal, cLocalAllocMap := (*C.char)(unsafe.Pointer(Local)), cgoAllocsUnknown
	cRemotes, cRemotesAllocMap := (**C.char)(unsafe.Pointer((*sliceHeader)(unsafe.Pointer(&Remotes)).Data)), cgoAllocsUnknown
	cRemotesSize, cRemotesSizeAllocMap := (*C.uint)(unsafe.Pointer(RemotesSize)), cgoAllocsUnknown
	cUuidSize, cUuidSizeAllocMap := (*C.uint)(unsafe.Pointer(UuidSize)), cgoAllocsUnknown
	__ret := C.mxSmlGetLocalAndMultipleRemoteUuid(cLocal, cRemotes, cRemotesSize, cUuidSize)
	runtime.KeepAlive(cUuidSizeAllocMap)
	runtime.KeepAlive(cRemotesSizeAllocMap)
	runtime.KeepAlive(cRemotesAllocMap)
	runtime.KeepAlive(cLocalAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetCurrentClocksThrottleReason function as declared in MxSml.h
func mxSmlGetCurrentClocksThrottleReason(DeviceId uint32, ClocksThrottleReasons *uint64) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cClocksThrottleReasons, cClocksThrottleReasonsAllocMap := (*C.ulonglong)(unsafe.Pointer(ClocksThrottleReasons)), cgoAllocsUnknown
	__ret := C.mxSmlGetCurrentClocksThrottleReason(cDeviceId, cClocksThrottleReasons)
	runtime.KeepAlive(cClocksThrottleReasonsAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetBoardPowerLimit function as declared in MxSml.h
func mxSmlGetBoardPowerLimit(DeviceId uint32, Limit *uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cLimit, cLimitAllocMap := (*C.uint)(unsafe.Pointer(Limit)), cgoAllocsUnknown
	__ret := C.mxSmlGetBoardPowerLimit(cDeviceId, cLimit)
	runtime.KeepAlive(cLimitAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetSgpuToggle function as declared in MxSml.h
func mxSmlGetSgpuToggle(DeviceId uint32, Toggle *uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cToggle, cToggleAllocMap := (*C.uint)(unsafe.Pointer(Toggle)), cgoAllocsUnknown
	__ret := C.mxSmlGetSgpuToggle(cDeviceId, cToggle)
	runtime.KeepAlive(cToggleAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlSetSgpuToggle function as declared in MxSml.h
func mxSmlSetSgpuToggle(DeviceId uint32, Toggle uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cToggle, cToggleAllocMap := (C.uint)(Toggle), cgoAllocsUnknown
	__ret := C.mxSmlSetSgpuToggle(cDeviceId, cToggle)
	runtime.KeepAlive(cToggleAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlCreateSgpu function as declared in MxSml.h
func mxSmlCreateSgpu(DeviceId uint32, Memory uint32, Compute uint32, SgpuId *uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cMemory, cMemoryAllocMap := (C.uint)(Memory), cgoAllocsUnknown
	cCompute, cComputeAllocMap := (C.uint)(Compute), cgoAllocsUnknown
	cSgpuId, cSgpuIdAllocMap := (*C.uint)(unsafe.Pointer(SgpuId)), cgoAllocsUnknown
	__ret := C.mxSmlCreateSgpu(cDeviceId, cMemory, cCompute, cSgpuId)
	runtime.KeepAlive(cSgpuIdAllocMap)
	runtime.KeepAlive(cComputeAllocMap)
	runtime.KeepAlive(cMemoryAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlRemoveSgpu function as declared in MxSml.h
func mxSmlRemoveSgpu(DeviceId uint32, SgpuId uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cSgpuId, cSgpuIdAllocMap := (C.uint)(SgpuId), cgoAllocsUnknown
	__ret := C.mxSmlRemoveSgpu(cDeviceId, cSgpuId)
	runtime.KeepAlive(cSgpuIdAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetSgpuCount function as declared in MxSml.h
func mxSmlGetSgpuCount(DeviceId uint32) uint32 {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	__ret := C.mxSmlGetSgpuCount(cDeviceId)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (uint32)(__ret)
	return __v
}

// mxSmlGetSgpuInfo function as declared in MxSml.h
func mxSmlGetSgpuInfo(DeviceId uint32, SgpuId uint32, SgpuInfo *MxSmlSgpuInfo) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cSgpuId, cSgpuIdAllocMap := (C.uint)(SgpuId), cgoAllocsUnknown
	cSgpuInfo, cSgpuInfoAllocMap := (*C.mxSmlSgpuInfo_t)(unsafe.Pointer(SgpuInfo)), cgoAllocsUnknown
	__ret := C.mxSmlGetSgpuInfo(cDeviceId, cSgpuId, cSgpuInfo)
	runtime.KeepAlive(cSgpuInfoAllocMap)
	runtime.KeepAlive(cSgpuIdAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlSetSgpuDeviceQueuePriority function as declared in MxSml.h
func mxSmlSetSgpuDeviceQueuePriority(DeviceId uint32, SgpuId uint32, DeviceQueuePriority uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cSgpuId, cSgpuIdAllocMap := (C.uint)(SgpuId), cgoAllocsUnknown
	cDeviceQueuePriority, cDeviceQueuePriorityAllocMap := (C.uint)(DeviceQueuePriority), cgoAllocsUnknown
	__ret := C.mxSmlSetSgpuDeviceQueuePriority(cDeviceId, cSgpuId, cDeviceQueuePriority)
	runtime.KeepAlive(cDeviceQueuePriorityAllocMap)
	runtime.KeepAlive(cSgpuIdAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetPciMmioState function as declared in MxSml.h
func mxSmlGetPciMmioState(DeviceId uint32, State *uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cState, cStateAllocMap := (*C.uint)(unsafe.Pointer(State)), cgoAllocsUnknown
	__ret := C.mxSmlGetPciMmioState(cDeviceId, cState)
	runtime.KeepAlive(cStateAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetPciEventInfo function as declared in MxSml.h
func mxSmlGetPciEventInfo(DeviceId uint32, EventType MxSmlPciEventType, EventInfos *MxSmlPciEventInfo, Size *uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cEventType, cEventTypeAllocMap := (C.mxSmlPciEventType_t)(EventType), cgoAllocsUnknown
	cEventInfos, cEventInfosAllocMap := (*C.mxSmlPciEventInfo_t)(unsafe.Pointer(EventInfos)), cgoAllocsUnknown
	cSize, cSizeAllocMap := (*C.uint)(unsafe.Pointer(Size)), cgoAllocsUnknown
	__ret := C.mxSmlGetPciEventInfo(cDeviceId, cEventType, cEventInfos, cSize)
	runtime.KeepAlive(cSizeAllocMap)
	runtime.KeepAlive(cEventInfosAllocMap)
	runtime.KeepAlive(cEventTypeAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetSgpuState function as declared in MxSml.h
func mxSmlGetSgpuState(DeviceId uint32, SgpuId uint32, State *int32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cSgpuId, cSgpuIdAllocMap := (C.uint)(SgpuId), cgoAllocsUnknown
	cState, cStateAllocMap := (*C.int)(unsafe.Pointer(State)), cgoAllocsUnknown
	__ret := C.mxSmlGetSgpuState(cDeviceId, cSgpuId, cState)
	runtime.KeepAlive(cStateAllocMap)
	runtime.KeepAlive(cSgpuIdAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlSetSgpuVramQuota function as declared in MxSml.h
func mxSmlSetSgpuVramQuota(DeviceId uint32, SgpuId uint32, Vram uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cSgpuId, cSgpuIdAllocMap := (C.uint)(SgpuId), cgoAllocsUnknown
	cVram, cVramAllocMap := (C.uint)(Vram), cgoAllocsUnknown
	__ret := C.mxSmlSetSgpuVramQuota(cDeviceId, cSgpuId, cVram)
	runtime.KeepAlive(cVramAllocMap)
	runtime.KeepAlive(cSgpuIdAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlSetSgpuComputeQuota function as declared in MxSml.h
func mxSmlSetSgpuComputeQuota(DeviceId uint32, SgpuId uint32, Compute uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cSgpuId, cSgpuIdAllocMap := (C.uint)(SgpuId), cgoAllocsUnknown
	cCompute, cComputeAllocMap := (C.uint)(Compute), cgoAllocsUnknown
	__ret := C.mxSmlSetSgpuComputeQuota(cDeviceId, cSgpuId, cCompute)
	runtime.KeepAlive(cComputeAllocMap)
	runtime.KeepAlive(cSgpuIdAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetSgpuAvailableQuota function as declared in MxSml.h
func mxSmlGetSgpuAvailableQuota(DeviceId uint32, AvailableInfo *MxSmlSgpuAvailableQuota) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cAvailableInfo, cAvailableInfoAllocMap := (*C.mxSmlSgpuAvailableQuota_t)(unsafe.Pointer(AvailableInfo)), cgoAllocsUnknown
	__ret := C.mxSmlGetSgpuAvailableQuota(cDeviceId, cAvailableInfo)
	runtime.KeepAlive(cAvailableInfoAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetSgpuUsage function as declared in MxSml.h
func mxSmlGetSgpuUsage(DeviceId uint32, SgpuId uint32, Usage *int32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cSgpuId, cSgpuIdAllocMap := (C.uint)(SgpuId), cgoAllocsUnknown
	cUsage, cUsageAllocMap := (*C.int)(unsafe.Pointer(Usage)), cgoAllocsUnknown
	__ret := C.mxSmlGetSgpuUsage(cDeviceId, cSgpuId, cUsage)
	runtime.KeepAlive(cUsageAllocMap)
	runtime.KeepAlive(cSgpuIdAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetSgpuMemory function as declared in MxSml.h
func mxSmlGetSgpuMemory(DeviceId uint32, SgpuId uint32, Memory *MxSmlSgpuMemoryInfo) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cSgpuId, cSgpuIdAllocMap := (C.uint)(SgpuId), cgoAllocsUnknown
	cMemory, cMemoryAllocMap := (*C.mxSmlSgpuMemoryInfo_t)(unsafe.Pointer(Memory)), cgoAllocsUnknown
	__ret := C.mxSmlGetSgpuMemory(cDeviceId, cSgpuId, cMemory)
	runtime.KeepAlive(cMemoryAllocMap)
	runtime.KeepAlive(cSgpuIdAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetDeviceTimeslice function as declared in MxSml.h
func mxSmlGetDeviceTimeslice(DeviceId uint32, Timeslice *uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cTimeslice, cTimesliceAllocMap := (*C.uint)(unsafe.Pointer(Timeslice)), cgoAllocsUnknown
	__ret := C.mxSmlGetDeviceTimeslice(cDeviceId, cTimeslice)
	runtime.KeepAlive(cTimesliceAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlSetDeviceTimeslice function as declared in MxSml.h
func mxSmlSetDeviceTimeslice(DeviceId uint32, Timeslice uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cTimeslice, cTimesliceAllocMap := (C.uint)(Timeslice), cgoAllocsUnknown
	__ret := C.mxSmlSetDeviceTimeslice(cDeviceId, cTimeslice)
	runtime.KeepAlive(cTimesliceAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetDeviceSchedClass function as declared in MxSml.h
func mxSmlGetDeviceSchedClass(DeviceId uint32, SchedClass *MxSmlSchedClass) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cSchedClass, cSchedClassAllocMap := (*C.mxSmlSchedClass_t)(unsafe.Pointer(SchedClass)), cgoAllocsUnknown
	__ret := C.mxSmlGetDeviceSchedClass(cDeviceId, cSchedClass)
	runtime.KeepAlive(cSchedClassAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlSetDeviceSchedClass function as declared in MxSml.h
func mxSmlSetDeviceSchedClass(DeviceId uint32, SchedClass MxSmlSchedClass) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cSchedClass, cSchedClassAllocMap := (C.mxSmlSchedClass_t)(SchedClass), cgoAllocsUnknown
	__ret := C.mxSmlSetDeviceSchedClass(cDeviceId, cSchedClass)
	runtime.KeepAlive(cSchedClassAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetSgpuAlias function as declared in MxSml.h
func mxSmlGetSgpuAlias(DeviceId uint32, SgpuId uint32, Alias *byte, Size *uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cSgpuId, cSgpuIdAllocMap := (C.uint)(SgpuId), cgoAllocsUnknown
	cAlias, cAliasAllocMap := (*C.char)(unsafe.Pointer(Alias)), cgoAllocsUnknown
	cSize, cSizeAllocMap := (*C.uint)(unsafe.Pointer(Size)), cgoAllocsUnknown
	__ret := C.mxSmlGetSgpuAlias(cDeviceId, cSgpuId, cAlias, cSize)
	runtime.KeepAlive(cSizeAllocMap)
	runtime.KeepAlive(cAliasAllocMap)
	runtime.KeepAlive(cSgpuIdAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlSetSgpuAlias function as declared in MxSml.h
func mxSmlSetSgpuAlias(DeviceId uint32, SgpuId uint32, Alias *byte) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cSgpuId, cSgpuIdAllocMap := (C.uint)(SgpuId), cgoAllocsUnknown
	cAlias, cAliasAllocMap := (*C.char)(unsafe.Pointer(Alias)), cgoAllocsUnknown
	__ret := C.mxSmlSetSgpuAlias(cDeviceId, cSgpuId, cAlias)
	runtime.KeepAlive(cAliasAllocMap)
	runtime.KeepAlive(cSgpuIdAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetDeviceIsaVersion function as declared in MxSml.h
func mxSmlGetDeviceIsaVersion(DeviceId uint32, IsaVersion *int32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cIsaVersion, cIsaVersionAllocMap := (*C.int)(unsafe.Pointer(IsaVersion)), cgoAllocsUnknown
	__ret := C.mxSmlGetDeviceIsaVersion(cDeviceId, cIsaVersion)
	runtime.KeepAlive(cIsaVersionAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetDeviceUnavailableReason function as declared in MxSml.h
func mxSmlGetDeviceUnavailableReason(DeviceId uint32, Reason *MxSmlDeviceUnavailableReasonInfo) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cReason, cReasonAllocMap := (*C.mxSmlDeviceUnavailableReasonInfo_t)(unsafe.Pointer(Reason)), cgoAllocsUnknown
	__ret := C.mxSmlGetDeviceUnavailableReason(cDeviceId, cReason)
	runtime.KeepAlive(cReasonAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetFanSpeedInfo function as declared in MxSml.h
func mxSmlGetFanSpeedInfo(DeviceId uint32, Rpm *uint32, Pwm *uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cRpm, cRpmAllocMap := (*C.uint)(unsafe.Pointer(Rpm)), cgoAllocsUnknown
	cPwm, cPwmAllocMap := (*C.uint)(unsafe.Pointer(Pwm)), cgoAllocsUnknown
	__ret := C.mxSmlGetFanSpeedInfo(cDeviceId, cRpm, cPwm)
	runtime.KeepAlive(cPwmAllocMap)
	runtime.KeepAlive(cRpmAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetSgpuAnnotationsId function as declared in MxSml.h
func mxSmlGetSgpuAnnotationsId(DeviceId uint32, SgpuId uint32, AnnotationsId *byte, Size *uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cSgpuId, cSgpuIdAllocMap := (C.uint)(SgpuId), cgoAllocsUnknown
	cAnnotationsId, cAnnotationsIdAllocMap := (*C.char)(unsafe.Pointer(AnnotationsId)), cgoAllocsUnknown
	cSize, cSizeAllocMap := (*C.uint)(unsafe.Pointer(Size)), cgoAllocsUnknown
	__ret := C.mxSmlGetSgpuAnnotationsId(cDeviceId, cSgpuId, cAnnotationsId, cSize)
	runtime.KeepAlive(cSizeAllocMap)
	runtime.KeepAlive(cAnnotationsIdAllocMap)
	runtime.KeepAlive(cSgpuIdAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetTotalEccErrors function as declared in MxSml.h
func mxSmlGetTotalEccErrors(DeviceId uint32, EccCounts *MxSmlEccErrorCount) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cEccCounts, cEccCountsAllocMap := (*C.mxSmlEccErrorCount_t)(unsafe.Pointer(EccCounts)), cgoAllocsUnknown
	__ret := C.mxSmlGetTotalEccErrors(cDeviceId, cEccCounts)
	runtime.KeepAlive(cEccCountsAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetDeviceBoardId function as declared in MxSml.h
func mxSmlGetDeviceBoardId(DeviceId uint32) int32 {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	__ret := C.mxSmlGetDeviceBoardId(cDeviceId)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (int32)(__ret)
	return __v
}

// mxSmlGetEthThroughput function as declared in MxSml.h
func mxSmlGetEthThroughput(DeviceId uint32, EthThroughput *MxSmlEthThroughput) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cEthThroughput, cEthThroughputAllocMap := (*C.mxSmlEthThroughput_t)(unsafe.Pointer(EthThroughput)), cgoAllocsUnknown
	__ret := C.mxSmlGetEthThroughput(cDeviceId, cEthThroughput)
	runtime.KeepAlive(cEthThroughputAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlEventSetCreate function as declared in MxSml.h
func mxSmlEventSetCreate(EventSet *MxSmlEventSet) MxSmlReturn {
	cEventSet, cEventSetAllocMap := (*C.mxSmlEventSet_t)(unsafe.Pointer(EventSet)), cgoAllocsUnknown
	__ret := C.mxSmlEventSetCreate(cEventSet)
	runtime.KeepAlive(cEventSetAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlDeviceRegisterEvents function as declared in MxSml.h
func mxSmlDeviceRegisterEvents(DeviceId uint32, EventTypes uint64, EventSet MxSmlEventSet) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cEventTypes, cEventTypesAllocMap := (C.ulonglong)(EventTypes), cgoAllocsUnknown
	cEventSet, cEventSetAllocMap := *(*C.mxSmlEventSet_t)(unsafe.Pointer(&EventSet)), cgoAllocsUnknown
	__ret := C.mxSmlDeviceRegisterEvents(cDeviceId, cEventTypes, cEventSet)
	runtime.KeepAlive(cEventSetAllocMap)
	runtime.KeepAlive(cEventTypesAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlEventSetWait function as declared in MxSml.h
func mxSmlEventSetWait(EventSet MxSmlEventSet, Data *MxSmlEvent) MxSmlReturn {
	cEventSet, cEventSetAllocMap := *(*C.mxSmlEventSet_t)(unsafe.Pointer(&EventSet)), cgoAllocsUnknown
	cData, cDataAllocMap := (*C.mxSmlEvent_t)(unsafe.Pointer(Data)), cgoAllocsUnknown
	__ret := C.mxSmlEventSetWait(cEventSet, cData)
	runtime.KeepAlive(cDataAllocMap)
	runtime.KeepAlive(cEventSetAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlEventSetFree function as declared in MxSml.h
func mxSmlEventSetFree(EventSet MxSmlEventSet) MxSmlReturn {
	cEventSet, cEventSetAllocMap := *(*C.mxSmlEventSet_t)(unsafe.Pointer(&EventSet)), cgoAllocsUnknown
	__ret := C.mxSmlEventSetFree(cEventSet)
	runtime.KeepAlive(cEventSetAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetDeviceDieCount function as declared in MxSmlMcm.h
func mxSmlGetDeviceDieCount(DeviceId uint32, DieCount *uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cDieCount, cDieCountAllocMap := (*C.uint)(unsafe.Pointer(DieCount)), cgoAllocsUnknown
	__ret := C.mxSmlGetDeviceDieCount(cDeviceId, cDieCount)
	runtime.KeepAlive(cDieCountAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetDieMemoryInfo function as declared in MxSmlMcm.h
func mxSmlGetDieMemoryInfo(DeviceId uint32, DieId uint32, MemoryInfo *MxSmlMemoryInfo) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cDieId, cDieIdAllocMap := (C.uint)(DieId), cgoAllocsUnknown
	cMemoryInfo, cMemoryInfoAllocMap := (*C.mxSmlMemoryInfo_t)(unsafe.Pointer(MemoryInfo)), cgoAllocsUnknown
	__ret := C.mxSmlGetDieMemoryInfo(cDeviceId, cDieId, cMemoryInfo)
	runtime.KeepAlive(cMemoryInfoAllocMap)
	runtime.KeepAlive(cDieIdAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetDieTemperatureInfo function as declared in MxSmlMcm.h
func mxSmlGetDieTemperatureInfo(DeviceId uint32, DieId uint32, TemperatureType MxSmlTemperatureSensors, Temperature *int32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cDieId, cDieIdAllocMap := (C.uint)(DieId), cgoAllocsUnknown
	cTemperatureType, cTemperatureTypeAllocMap := (C.mxSmlTemperatureSensors_t)(TemperatureType), cgoAllocsUnknown
	cTemperature, cTemperatureAllocMap := (*C.int)(unsafe.Pointer(Temperature)), cgoAllocsUnknown
	__ret := C.mxSmlGetDieTemperatureInfo(cDeviceId, cDieId, cTemperatureType, cTemperature)
	runtime.KeepAlive(cTemperatureAllocMap)
	runtime.KeepAlive(cTemperatureTypeAllocMap)
	runtime.KeepAlive(cDieIdAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetDiePmbusInfo function as declared in MxSmlMcm.h
func mxSmlGetDiePmbusInfo(DeviceId uint32, DieId uint32, PmbusUnit MxSmlPmbusUnit, PmbusInfo *MxSmlPmbusInfo) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cDieId, cDieIdAllocMap := (C.uint)(DieId), cgoAllocsUnknown
	cPmbusUnit, cPmbusUnitAllocMap := (C.mxSmlPmbusUnit_t)(PmbusUnit), cgoAllocsUnknown
	cPmbusInfo, cPmbusInfoAllocMap := (*C.mxSmlPmbusInfo_t)(unsafe.Pointer(PmbusInfo)), cgoAllocsUnknown
	__ret := C.mxSmlGetDiePmbusInfo(cDeviceId, cDieId, cPmbusUnit, cPmbusInfo)
	runtime.KeepAlive(cPmbusInfoAllocMap)
	runtime.KeepAlive(cPmbusUnitAllocMap)
	runtime.KeepAlive(cDieIdAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetDeviceDieVersion function as declared in MxSmlMcm.h
func mxSmlGetDeviceDieVersion(DeviceId uint32, DieId uint32, VersionUnit MxSmlVersionUnit, Version *byte, Size *uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cDieId, cDieIdAllocMap := (C.uint)(DieId), cgoAllocsUnknown
	cVersionUnit, cVersionUnitAllocMap := (C.mxSmlVersionUnit_t)(VersionUnit), cgoAllocsUnknown
	cVersion, cVersionAllocMap := (*C.char)(unsafe.Pointer(Version)), cgoAllocsUnknown
	cSize, cSizeAllocMap := (*C.uint)(unsafe.Pointer(Size)), cgoAllocsUnknown
	__ret := C.mxSmlGetDeviceDieVersion(cDeviceId, cDieId, cVersionUnit, cVersion, cSize)
	runtime.KeepAlive(cSizeAllocMap)
	runtime.KeepAlive(cVersionAllocMap)
	runtime.KeepAlive(cVersionUnitAllocMap)
	runtime.KeepAlive(cDieIdAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetDieClocks function as declared in MxSmlMcm.h
func mxSmlGetDieClocks(DeviceId uint32, DieId uint32, ClockIp MxSmlClockIp, ClocksSize *uint32, ClocksMhz *uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cDieId, cDieIdAllocMap := (C.uint)(DieId), cgoAllocsUnknown
	cClockIp, cClockIpAllocMap := (C.mxSmlClockIp_t)(ClockIp), cgoAllocsUnknown
	cClocksSize, cClocksSizeAllocMap := (*C.uint)(unsafe.Pointer(ClocksSize)), cgoAllocsUnknown
	cClocksMhz, cClocksMhzAllocMap := (*C.uint)(unsafe.Pointer(ClocksMhz)), cgoAllocsUnknown
	__ret := C.mxSmlGetDieClocks(cDeviceId, cDieId, cClockIp, cClocksSize, cClocksMhz)
	runtime.KeepAlive(cClocksMhzAllocMap)
	runtime.KeepAlive(cClocksSizeAllocMap)
	runtime.KeepAlive(cClockIpAllocMap)
	runtime.KeepAlive(cDieIdAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetDieChipSerial function as declared in MxSmlMcm.h
func mxSmlGetDieChipSerial(DeviceId uint32, DieId uint32, ChipSerial *byte, Size *uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cDieId, cDieIdAllocMap := (C.uint)(DieId), cgoAllocsUnknown
	cChipSerial, cChipSerialAllocMap := (*C.char)(unsafe.Pointer(ChipSerial)), cgoAllocsUnknown
	cSize, cSizeAllocMap := (*C.uint)(unsafe.Pointer(Size)), cgoAllocsUnknown
	__ret := C.mxSmlGetDieChipSerial(cDeviceId, cDieId, cChipSerial, cSize)
	runtime.KeepAlive(cSizeAllocMap)
	runtime.KeepAlive(cChipSerialAllocMap)
	runtime.KeepAlive(cDieIdAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetDieIpUsage function as declared in MxSmlMcm.h
func mxSmlGetDieIpUsage(DeviceId uint32, DieId uint32, Ip MxSmlUsageIp, Usage *int32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cDieId, cDieIdAllocMap := (C.uint)(DieId), cgoAllocsUnknown
	cIp, cIpAllocMap := (C.mxSmlUsageIp_t)(Ip), cgoAllocsUnknown
	cUsage, cUsageAllocMap := (*C.int)(unsafe.Pointer(Usage)), cgoAllocsUnknown
	__ret := C.mxSmlGetDieIpUsage(cDeviceId, cDieId, cIp, cUsage)
	runtime.KeepAlive(cUsageAllocMap)
	runtime.KeepAlive(cIpAllocMap)
	runtime.KeepAlive(cDieIdAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetDieApUsageToggle function as declared in MxSmlMcm.h
func mxSmlGetDieApUsageToggle(DeviceId uint32, DieId uint32, ApUsageToggle *uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cDieId, cDieIdAllocMap := (C.uint)(DieId), cgoAllocsUnknown
	cApUsageToggle, cApUsageToggleAllocMap := (*C.uint)(unsafe.Pointer(ApUsageToggle)), cgoAllocsUnknown
	__ret := C.mxSmlGetDieApUsageToggle(cDeviceId, cDieId, cApUsageToggle)
	runtime.KeepAlive(cApUsageToggleAllocMap)
	runtime.KeepAlive(cDieIdAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetCurrentDieDpmIpPerfLevel function as declared in MxSmlMcm.h
func mxSmlGetCurrentDieDpmIpPerfLevel(DeviceId uint32, DieId uint32, DpmIp MxSmlDpmIp, DpmIpPerfLevel *uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cDieId, cDieIdAllocMap := (C.uint)(DieId), cgoAllocsUnknown
	cDpmIp, cDpmIpAllocMap := (C.mxSmlDpmIp_t)(DpmIp), cgoAllocsUnknown
	cDpmIpPerfLevel, cDpmIpPerfLevelAllocMap := (*C.uint)(unsafe.Pointer(DpmIpPerfLevel)), cgoAllocsUnknown
	__ret := C.mxSmlGetCurrentDieDpmIpPerfLevel(cDeviceId, cDieId, cDpmIp, cDpmIpPerfLevel)
	runtime.KeepAlive(cDpmIpPerfLevelAllocMap)
	runtime.KeepAlive(cDpmIpAllocMap)
	runtime.KeepAlive(cDieIdAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetDieDpmIpMaxPerfLevel function as declared in MxSmlMcm.h
func mxSmlGetDieDpmIpMaxPerfLevel(DeviceId uint32, DieId uint32, DpmIp MxSmlDpmIp, DpmMaxLevel *uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cDieId, cDieIdAllocMap := (C.uint)(DieId), cgoAllocsUnknown
	cDpmIp, cDpmIpAllocMap := (C.mxSmlDpmIp_t)(DpmIp), cgoAllocsUnknown
	cDpmMaxLevel, cDpmMaxLevelAllocMap := (*C.uint)(unsafe.Pointer(DpmMaxLevel)), cgoAllocsUnknown
	__ret := C.mxSmlGetDieDpmIpMaxPerfLevel(cDeviceId, cDieId, cDpmIp, cDpmMaxLevel)
	runtime.KeepAlive(cDpmMaxLevelAllocMap)
	runtime.KeepAlive(cDpmIpAllocMap)
	runtime.KeepAlive(cDieIdAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetDieCodecStatus function as declared in MxSmlMcm.h
func mxSmlGetDieCodecStatus(DeviceId uint32, DieId uint32, CodecStatus *MxSmlCodecStatus) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cDieId, cDieIdAllocMap := (C.uint)(DieId), cgoAllocsUnknown
	cCodecStatus, cCodecStatusAllocMap := (*C.mxSmlCodecStatus_t)(unsafe.Pointer(CodecStatus)), cgoAllocsUnknown
	__ret := C.mxSmlGetDieCodecStatus(cDeviceId, cDieId, cCodecStatus)
	runtime.KeepAlive(cCodecStatusAllocMap)
	runtime.KeepAlive(cDieIdAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetDieXcoreApUsage function as declared in MxSmlMcm.h
func mxSmlGetDieXcoreApUsage(DeviceId uint32, DieId uint32, ApUsage *uint32, Size *uint32, DpcNum *uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cDieId, cDieIdAllocMap := (C.uint)(DieId), cgoAllocsUnknown
	cApUsage, cApUsageAllocMap := (*C.uint)(unsafe.Pointer(ApUsage)), cgoAllocsUnknown
	cSize, cSizeAllocMap := (*C.uint)(unsafe.Pointer(Size)), cgoAllocsUnknown
	cDpcNum, cDpcNumAllocMap := (*C.uint)(unsafe.Pointer(DpcNum)), cgoAllocsUnknown
	__ret := C.mxSmlGetDieXcoreApUsage(cDeviceId, cDieId, cApUsage, cSize, cDpcNum)
	runtime.KeepAlive(cDpcNumAllocMap)
	runtime.KeepAlive(cSizeAllocMap)
	runtime.KeepAlive(cApUsageAllocMap)
	runtime.KeepAlive(cDieIdAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetDieEepromInfo function as declared in MxSmlMcm.h
func mxSmlGetDieEepromInfo(DeviceId uint32, DieId uint32, EepromInfo *MxSmlEepromInfo) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cDieId, cDieIdAllocMap := (C.uint)(DieId), cgoAllocsUnknown
	cEepromInfo, cEepromInfoAllocMap := (*C.mxSmlEepromInfo_t)(unsafe.Pointer(EepromInfo)), cgoAllocsUnknown
	__ret := C.mxSmlGetDieEepromInfo(cDeviceId, cDieId, cEepromInfo)
	runtime.KeepAlive(cEepromInfoAllocMap)
	runtime.KeepAlive(cDieIdAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetDieEccState function as declared in MxSmlMcm.h
func mxSmlGetDieEccState(DeviceId uint32, DieId uint32, EccState *uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cDieId, cDieIdAllocMap := (C.uint)(DieId), cgoAllocsUnknown
	cEccState, cEccStateAllocMap := (*C.uint)(unsafe.Pointer(EccState)), cgoAllocsUnknown
	__ret := C.mxSmlGetDieEccState(cDeviceId, cDieId, cEccState)
	runtime.KeepAlive(cEccStateAllocMap)
	runtime.KeepAlive(cDieIdAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetDiePowerStateInfo function as declared in MxSmlMcm.h
func mxSmlGetDiePowerStateInfo(DeviceId uint32, DieId uint32, DpmIp MxSmlDpmIp, PowerState *int32, Size *uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cDieId, cDieIdAllocMap := (C.uint)(DieId), cgoAllocsUnknown
	cDpmIp, cDpmIpAllocMap := (C.mxSmlDpmIp_t)(DpmIp), cgoAllocsUnknown
	cPowerState, cPowerStateAllocMap := (*C.int)(unsafe.Pointer(PowerState)), cgoAllocsUnknown
	cSize, cSizeAllocMap := (*C.uint)(unsafe.Pointer(Size)), cgoAllocsUnknown
	__ret := C.mxSmlGetDiePowerStateInfo(cDeviceId, cDieId, cDpmIp, cPowerState, cSize)
	runtime.KeepAlive(cSizeAllocMap)
	runtime.KeepAlive(cPowerStateAllocMap)
	runtime.KeepAlive(cDpmIpAllocMap)
	runtime.KeepAlive(cDieIdAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetDieHbmBandWidth function as declared in MxSmlMcm.h
func mxSmlGetDieHbmBandWidth(DeviceId uint32, DieId uint32, HbmBandWidth *MxSmlHbmBandWidth) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cDieId, cDieIdAllocMap := (C.uint)(DieId), cgoAllocsUnknown
	cHbmBandWidth, cHbmBandWidthAllocMap := (*C.mxSmlHbmBandWidth_t)(unsafe.Pointer(HbmBandWidth)), cgoAllocsUnknown
	__ret := C.mxSmlGetDieHbmBandWidth(cDeviceId, cDieId, cHbmBandWidth)
	runtime.KeepAlive(cHbmBandWidthAllocMap)
	runtime.KeepAlive(cDieIdAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetDiePptableVersion function as declared in MxSmlMcm.h
func mxSmlGetDiePptableVersion(DeviceId uint32, DieId uint32, Size uint32, Version *byte) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cDieId, cDieIdAllocMap := (C.uint)(DieId), cgoAllocsUnknown
	cSize, cSizeAllocMap := (C.uint)(Size), cgoAllocsUnknown
	cVersion, cVersionAllocMap := (*C.char)(unsafe.Pointer(Version)), cgoAllocsUnknown
	__ret := C.mxSmlGetDiePptableVersion(cDeviceId, cDieId, cSize, cVersion)
	runtime.KeepAlive(cVersionAllocMap)
	runtime.KeepAlive(cSizeAllocMap)
	runtime.KeepAlive(cDieIdAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetDieRasStatusData function as declared in MxSmlMcm.h
func mxSmlGetDieRasStatusData(DeviceId uint32, DieId uint32, RasStatusData *MxSmlRasStatusData) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cDieId, cDieIdAllocMap := (C.uint)(DieId), cgoAllocsUnknown
	cRasStatusData, cRasStatusDataAllocMap := (*C.mxSmlRasStatusData_t)(unsafe.Pointer(RasStatusData)), cgoAllocsUnknown
	__ret := C.mxSmlGetDieRasStatusData(cDeviceId, cDieId, cRasStatusData)
	runtime.KeepAlive(cRasStatusDataAllocMap)
	runtime.KeepAlive(cDieIdAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetDieRasErrorData function as declared in MxSmlMcm.h
func mxSmlGetDieRasErrorData(DeviceId uint32, DieId uint32, RasErrorData *MxSmlRasErrorData) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cDieId, cDieIdAllocMap := (C.uint)(DieId), cgoAllocsUnknown
	cRasErrorData, cRasErrorDataAllocMap := (*C.mxSmlRasErrorData_t)(unsafe.Pointer(RasErrorData)), cgoAllocsUnknown
	__ret := C.mxSmlGetDieRasErrorData(cDeviceId, cDieId, cRasErrorData)
	runtime.KeepAlive(cRasErrorDataAllocMap)
	runtime.KeepAlive(cDieIdAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetDieMetaXLinkRemoteInfo function as declared in MxSmlMcm.h
func mxSmlGetDieMetaXLinkRemoteInfo(DeviceId uint32, DieId uint32, LinkId uint32, Remote *MxSmlMcmMetaXLinkRemoteInfo) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cDieId, cDieIdAllocMap := (C.uint)(DieId), cgoAllocsUnknown
	cLinkId, cLinkIdAllocMap := (C.uint)(LinkId), cgoAllocsUnknown
	cRemote, cRemoteAllocMap := (*C.mxSmlMcmMetaXLinkRemoteInfo_t)(unsafe.Pointer(Remote)), cgoAllocsUnknown
	__ret := C.mxSmlGetDieMetaXLinkRemoteInfo(cDeviceId, cDieId, cLinkId, cRemote)
	runtime.KeepAlive(cRemoteAllocMap)
	runtime.KeepAlive(cLinkIdAllocMap)
	runtime.KeepAlive(cDieIdAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetDieDmaBandwidth function as declared in MxSmlMcm.h
func mxSmlGetDieDmaBandwidth(DeviceId uint32, DieId uint32, DmaBandwidth *MxSmlDmaEngineBandwidth, Size *uint32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cDieId, cDieIdAllocMap := (C.uint)(DieId), cgoAllocsUnknown
	cDmaBandwidth, cDmaBandwidthAllocMap := (*C.mxSmlDmaEngineBandwidth_t)(unsafe.Pointer(DmaBandwidth)), cgoAllocsUnknown
	cSize, cSizeAllocMap := (*C.uint)(unsafe.Pointer(Size)), cgoAllocsUnknown
	__ret := C.mxSmlGetDieDmaBandwidth(cDeviceId, cDieId, cDmaBandwidth, cSize)
	runtime.KeepAlive(cSizeAllocMap)
	runtime.KeepAlive(cDmaBandwidthAllocMap)
	runtime.KeepAlive(cDieIdAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlSetDieApUsageToggle function as declared in MxSmlMcm.h
func mxSmlSetDieApUsageToggle(DeviceId uint32, DieId uint32, Toggle int32) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cDieId, cDieIdAllocMap := (C.uint)(DieId), cgoAllocsUnknown
	cToggle, cToggleAllocMap := (C.int)(Toggle), cgoAllocsUnknown
	__ret := C.mxSmlSetDieApUsageToggle(cDeviceId, cDieId, cToggle)
	runtime.KeepAlive(cToggleAllocMap)
	runtime.KeepAlive(cDieIdAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetDieUnavailableReason function as declared in MxSmlMcm.h
func mxSmlGetDieUnavailableReason(DeviceId uint32, DieId uint32, Reason *MxSmlDeviceUnavailableReasonInfo) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cDieId, cDieIdAllocMap := (C.uint)(DieId), cgoAllocsUnknown
	cReason, cReasonAllocMap := (*C.mxSmlDeviceUnavailableReasonInfo_t)(unsafe.Pointer(Reason)), cgoAllocsUnknown
	__ret := C.mxSmlGetDieUnavailableReason(cDeviceId, cDieId, cReason)
	runtime.KeepAlive(cReasonAllocMap)
	runtime.KeepAlive(cDieIdAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetDieTotalEccErrors function as declared in MxSmlMcm.h
func mxSmlGetDieTotalEccErrors(DeviceId uint32, DieId uint32, EccCounts *MxSmlEccErrorCount) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cDieId, cDieIdAllocMap := (C.uint)(DieId), cgoAllocsUnknown
	cEccCounts, cEccCountsAllocMap := (*C.mxSmlEccErrorCount_t)(unsafe.Pointer(EccCounts)), cgoAllocsUnknown
	__ret := C.mxSmlGetDieTotalEccErrors(cDeviceId, cDieId, cEccCounts)
	runtime.KeepAlive(cEccCountsAllocMap)
	runtime.KeepAlive(cDieIdAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}

// mxSmlGetDieCurrentClocksThrottleReason function as declared in MxSmlMcm.h
func mxSmlGetDieCurrentClocksThrottleReason(DeviceId uint32, DieId uint32, ClocksThrottleReasons *uint64) MxSmlReturn {
	cDeviceId, cDeviceIdAllocMap := (C.uint)(DeviceId), cgoAllocsUnknown
	cDieId, cDieIdAllocMap := (C.uint)(DieId), cgoAllocsUnknown
	cClocksThrottleReasons, cClocksThrottleReasonsAllocMap := (*C.ulonglong)(unsafe.Pointer(ClocksThrottleReasons)), cgoAllocsUnknown
	__ret := C.mxSmlGetDieCurrentClocksThrottleReason(cDeviceId, cDieId, cClocksThrottleReasons)
	runtime.KeepAlive(cClocksThrottleReasonsAllocMap)
	runtime.KeepAlive(cDieIdAllocMap)
	runtime.KeepAlive(cDeviceIdAllocMap)
	__v := (MxSmlReturn)(__ret)
	return __v
}
