// Code generated by cmd/cgo -godefs; DO NOT EDIT.
// cgo -godefs types.go

package mxsml

type MxSmlDeviceInfo struct {
	DeviceId   uint32
	Type       uint32
	BdfId      [32]int8
	GpuId      uint32
	NodeId     uint32
	Uuid       [96]int8
	Brand      uint32
	Mode       uint32
	DeviceName [32]int8
}

type MxSmlRasRegister struct {
	RasIp         uint32
	RegisterIndex uint32
	RegisterData  int32
}

type MxSmlRasErrorRegister_v2 struct {
	RasIp      uint32
	RasErrorUe int32
	RasErrorCe int32
}

type MxSmlRasStatusData struct {
	RasStatusRegister [128]MxSmlRasRegister
	ShowRasStatusSize int32
}

type MxSmlRasErrorRegister struct {
	RasIp         uint32
	RegisterIndex uint32
	RasErrorUe    int32
	RasErrorCe    int32
}

type MxSmlRasErrorData struct {
	RasErrorRegister [128]MxSmlRasErrorRegister
	ShowRasErrorSize int32
}

type MxSmlRasErrorData_v2 struct {
	RasErrorRegister [128]MxSmlRasErrorRegister_v2
	ShowRasErrorSize int32
}

type MxSmlEepromInfo struct {
	Content [1024]int8
}

type MxSmlMemoryInfo struct {
	VisVramTotal int64
	VisVramUse   int64
	VramTotal    int64
	VramUse      int64
	XttTotal     int64
	XttUse       int64
}

type MxSmlPcieInfo struct {
	Speed float32
	Width uint32
}

type MxSmlHbmBandWidth struct {
	HbmBandwidthReqTotal  int32
	HbmBandwidthRespTotal int32
}

type MxSmlDmaEngineBandwidth struct {
	ReadReqBandwidth   int32
	ReadRespBandwidth  int32
	WriteReqBandwidth  int32
	WriteRespBandwidth int32
}

type MxSmlVirtualDeviceIds struct {
	Number   int32
	DeviceId [128]int32
}

type MxSmlLimitedDeviceIds struct {
	Number   int32
	DeviceId [128]int32
}

type MxSmlProcessGpuInfo struct {
	BdfId          [32]int8
	GpuId          uint32
	GpuMemoryUsage uint64
}

type MxSmlProcessInfo struct {
	ProcessId      uint32
	ProcessName    [64]int8
	GpuNumber      uint32
	ProcessGpuInfo [64]MxSmlProcessGpuInfo
}

type MxSmlProcessGpuInfo_v2 struct {
	BdfId          [32]int8
	GpuId          uint32
	GpuMemoryUsage uint64
	DieId          uint32
	Pad_cgo_0      [4]byte
}

type MxSmlProcessInfo_v2 struct {
	ProcessId      uint32
	ProcessName    [64]int8
	GpuNumber      uint32
	ProcessGpuInfo [64]MxSmlProcessGpuInfo_v2
}

type MxSmlProcessGpuInfo_v3 struct {
	BdfId          [32]int8
	GpuId          uint32
	GpuMemoryUsage uint64
	DieId          uint32
	SgpuId         int32
}

type MxSmlProcessInfo_v3 struct {
	ProcessId      uint32
	ProcessName    [64]int8
	GpuNumber      uint32
	ProcessGpuInfo [64]MxSmlProcessGpuInfo_v3
}

type MxSmlPmbusInfo struct {
	Voltage uint32
	Current uint32
	Power   uint32
}

type MxSmlBoardWayElectricInfo struct {
	Voltage uint32
	Current uint32
	Power   uint32
}

type MxSmlMxcDpmPerfLevel struct {
	Xcore uint32
	Mc    uint32
	Soc   uint32
	Dnoc  uint32
	Vpue  uint32
	Vpud  uint32
	Ccx   uint32
}

type MxSmlVpuStatus struct {
	Vpue0 int32
	Vpue1 int32
	Vpud0 int32
}

type MxSmlCodecStatus struct {
	Encoder int32
	Decoder int32
}

type MxSmlPcieThroughput struct {
	Rx int32
	Tx int32
}

type MxSmlMetaXLinkInfo struct {
	Speed [7]float32
	Width [7]uint32
}

type MxSmlSingleMxlkInfo struct {
	Speed float32
	Width uint32
}

type MxSmlMetaXLinkBandwidth struct {
	RequestBandwidth  int32
	ResponseBandwidth int32
}

type MxSmlMetaXLinkTrafficStat struct {
	RequestTrafficStat  int64
	ResponseTrafficStat int64
}

type MxSmlMetaXLinkAer struct {
	CeAer int32
	UeAer int32
}

type MxSmlMetaXLinkRemoteInfo struct {
	DeviceId int32
	BdfId    [32]int8
}

type MxSmlMetaXLinkTopo struct {
	TopologyId uint32
	SocketId   uint32
	DieId      uint32
}

type MxSmlVbiosUpgradeArg struct {
	TimeLimit    uint32
	VbiosBinPath [151]int8
	ForceUpgrade int32
	Ret          uint32
	PfBar0Size   int32
	VfBar0Size   int32
}

type MxSmlFwLoglevel struct {
	SmpCount uint32
	Smp      [2]uint32
	CcxCount uint32
	Ccx      [4]uint32
}

type MxSmlOpticalModuleStatus struct {
	Temperature   int32
	Voltage       uint32
	ModuleState   uint32
	DataPathState uint32
	RxState       [2]uint32
	Version       [2]uint32
}

type MxSmlOpticalModuleInfo struct {
	Name [32]int8
	Oui  [3]uint32
	Pn   [32]int8
	Rev  [32]int8
	Sn   [32]int8
}

type MxSmlOpticalModulePower struct {
	Value [8]uint32
}

type MxSmlSgpuInfo struct {
	ParentDeviceId      uint32
	SgpuId              uint32
	VramQuota           uint32
	SwQueuePriority     uint32
	ComputeQuota        uint32
	Minor               uint32
	DeviceQueuePriority uint32
	Uuid                [96]int8
}

type MxSmlPciEventInfo struct {
	BitNumber int32
	Count     int32
	FirstTime [20]int8
	Name      [64]int8
}

type MxSmlSgpuAvailableQuota struct {
	TotalVramQuota uint32
	VramQuota      uint32
	ComputeQuota   uint32
}

type MxSmlSgpuMemoryInfo struct {
	Total int64
	Used  int64
	Free  int64
}

type MxSmlDeviceUnavailableReasonInfo struct {
	UnavailableCode   int32
	UnavailableReason [64]int8
}

type MxSmlEccErrorCount struct {
	SramCE      uint32
	SramUE      uint32
	DramCE      uint32
	DramUE      uint32
	RetiredPage uint32
}

type MxSmlEthThroughput struct {
	Rx int32
	Tx int32
}

type MxSmlEventSet *_Ctype_struct_mxSmlEventSetImpl_t

type MxSmlEvent struct {
	DeviceId  int32
	Type      int32
	EventData [1024]int8
}

type MxSmlMcmMetaXLinkRemoteInfo struct {
	DeviceId int32
	BdfId    [32]int8
	DieId    uint32
}
